export interface PortfolioProject {
  title: string
  industry: string
  brief: string
  howTo: string
  tools: string[]
  artifact: string
}

export interface CoursePortfolio {
  green: PortfolioProject[]
  blue: PortfolioProject[]
  black: PortfolioProject[]
}

export const PORTFOLIO_PROJECTS: Record<string, CoursePortfolio> = {
  cybersecurity: {
    green: [
      {
        title: 'Personal Cybersecurity Audit Report',
        industry: 'Personal / Any',
        brief: 'Conduct a full security audit of your own digital footprint covering accounts, passwords, social media exposure, and device security.',
        howTo: 'Enumerate all online accounts. Check breached credentials on HaveIBeenPwned. Review social media privacy settings. Test home network with Nmap. Document findings and produce a remediation report.',
        tools: ['HaveIBeenPwned', 'Nmap', 'Bitwarden', 'Maltego CE', 'PasswordCheckup'],
        artifact: 'Personal Cybersecurity Audit PDF with remediation checklist and before/after screenshots.',
      },
      {
        title: 'School Network Security Assessment',
        industry: 'Education',
        brief: 'Identify and document vulnerabilities in a simulated school LAN environment representing a Nigerian secondary school.',
        howTo: 'Build a virtual lab with VirtualBox replicating a school network. Run a port scan, identify open services, test default router credentials, and produce a school-friendly remediation report.',
        tools: ['VirtualBox', 'Nmap', 'Nessus Essentials', 'Wireshark'],
        artifact: 'School Network Vulnerability Assessment Report and Remediation Roadmap.',
      },
      {
        title: 'Hospital Staff Phishing Awareness Campaign',
        industry: 'Healthcare',
        brief: 'Design and simulate a phishing campaign targeting a fictional hospital, then deliver a staff awareness training module.',
        howTo: 'Use GoPhish to send simulated phishing emails to fictional staff accounts. Record click rates. Build a 10-slide awareness training deck. Measure improvement in a follow-up simulated attack.',
        tools: ['GoPhish', 'Mailtrap', 'Canva', 'MXToolbox'],
        artifact: 'Phishing Campaign Report with click-rate statistics and Staff Awareness Training Module.',
      },
      {
        title: 'Home Router Hardening Guide',
        industry: 'Telecommunications',
        brief: 'Research and test home router security weaknesses, then produce a practical hardening guide for everyday Nigerian households.',
        howTo: 'Set up a test router in a lab. Test default credentials, open ports, firmware version, DNS settings, and WPS vulnerabilities. Write a step-by-step hardening guide with screenshots.',
        tools: ['Nmap', 'Router admin panel', 'Kali Linux', 'Python port scanner'],
        artifact: 'Home Router Hardening Guide (PDF) with screenshots and remediation checklist.',
      },
      {
        title: 'Mobile Money Social Engineering Awareness Video',
        industry: 'Social / Fintech',
        brief: 'Build a public awareness campaign about social engineering attacks targeting Nigerian mobile money users: OTP fraud, SIM swap, and impersonation.',
        howTo: 'Research common attacks on mobile money platforms. Script and produce a 5-minute explainer video. Add a digital quiz. Publish on YouTube or social media.',
        tools: ['Canva', 'CapCut or DaVinci Resolve', 'Google Forms'],
        artifact: 'Published Awareness Video (YouTube/Social) and Digital Safety Quiz.',
      },
      {
        title: 'Secure Password Manager Deployment for an SME',
        industry: 'Retail / Business',
        brief: 'Deploy and configure an open-source password manager for a fictional small business with 10 staff members.',
        howTo: 'Install Bitwarden self-hosted on a local VM. Configure user accounts, vault sharing policies, and enforce 2FA. Write a deployment guide and user onboarding document.',
        tools: ['VirtualBox', 'Bitwarden Self-Hosted', 'Docker'],
        artifact: 'Password Manager Deployment Guide and Staff Onboarding Document.',
      },
      {
        title: 'E-Commerce Website OWASP Security Checklist',
        industry: 'Retail / E-Commerce',
        brief: 'Audit a sample e-commerce site for OWASP Top 10 vulnerabilities and produce a developer-ready security checklist.',
        howTo: 'Set up DVWA locally. Test for SQL injection, XSS, CSRF, broken authentication, and insecure direct object references. Document each and write fix recommendations.',
        tools: ['OWASP ZAP', 'Burp Suite Community', 'DVWA', 'Kali Linux'],
        artifact: 'E-Commerce Security Audit Report and OWASP Top 10 Remediation Checklist.',
      },
      {
        title: 'Agritech Data Breach Incident Response Plan',
        industry: 'Agriculture',
        brief: 'Create a cyber incident response plan for a fictional Nigerian agritech startup that has experienced a customer data breach.',
        howTo: 'Research Nigeria Data Protection Act 2023 breach notification requirements. Draft an IRP covering detection, containment, eradication, recovery, and NDPC notification. Run a tabletop exercise.',
        tools: ['Microsoft Word', 'NIST IR framework', 'NDPA 2023'],
        artifact: 'Incident Response Plan and Tabletop Exercise Summary Report.',
      },
      {
        title: 'Government Web Portal Vulnerability Disclosure Report',
        industry: 'Government',
        brief: 'Perform a responsible, educational vulnerability assessment of a simulated government web application and write a disclosure report.',
        howTo: 'Set up DVWA themed as a government portal. Run a structured assessment. Document vulnerabilities following responsible disclosure principles. Write a formal disclosure letter.',
        tools: ['OWASP ZAP', 'Burp Suite Community', 'DVWA'],
        artifact: 'Vulnerability Disclosure Report and sample Responsible Disclosure Letter.',
      },
      {
        title: 'Oil and Gas Company Cybersecurity Policy Draft',
        industry: 'Oil and Gas',
        brief: 'Research cybersecurity requirements for Nigerian oil and gas operators and draft a company-level cybersecurity policy.',
        howTo: 'Research NUPRC cybersecurity directives and NIST CSF. Create a fictional scenario. Draft a policy covering access control, incident response, OT/IT security, and remote access management.',
        tools: ['NIST CSF', 'ISO 27001 reference', 'Microsoft Word'],
        artifact: 'Company Cybersecurity Policy Document (10+ pages) with implementation roadmap.',
      },
    ],
    blue: [
      {
        title: 'Fintech SOC Monitoring Lab and Dashboard',
        industry: 'Fintech / Banking',
        brief: 'Build a functional Security Operations Centre lab simulating a Nigerian commercial bank\'s threat monitoring environment.',
        howTo: 'Deploy Wazuh SIEM on VirtualBox. Configure agents on Windows and Linux endpoints. Write 5 custom detection rules for banking threats (login spike, port scan, USB insertion). Build a live dashboard.',
        tools: ['Wazuh', 'VirtualBox', 'Elastic Stack', 'Sysmon', 'Python'],
        artifact: 'Live SOC Dashboard walkthrough video and detection rule repository on GitHub.',
      },
      {
        title: 'Hospital Network Intrusion Detection System',
        industry: 'Healthcare',
        brief: 'Deploy a full IDS/IPS solution protecting a fictional hospital patient records network from common attack patterns.',
        howTo: 'Set up Suricata on a Linux VM connected to a simulated hospital VLAN. Write 10 custom rules covering medical device scanning, ransomware beaconing, and lateral movement. Test with Metasploit.',
        tools: ['Suricata', 'Wireshark', 'Metasploit', 'VirtualBox', 'PfSense'],
        artifact: 'Network Defence Architecture Diagram, Custom IDS Ruleset on GitHub, and Attack Simulation Report.',
      },
      {
        title: 'Agritech AWS Cloud Security Compliance Audit',
        industry: 'Agriculture / Technology',
        brief: 'Audit an AWS cloud infrastructure for a fictional Nigerian agritech startup against CIS Benchmark compliance standards.',
        howTo: 'Set up an AWS free tier account with intentional misconfigurations. Run Prowler and ScoutSuite. Produce a prioritised remediation report with Terraform-based fixes.',
        tools: ['AWS CLI', 'Prowler', 'ScoutSuite', 'Terraform', 'Python'],
        artifact: 'Cloud Security Audit Report and automated Terraform remediation scripts on GitHub.',
      },
      {
        title: 'E-Commerce Web Application Penetration Test',
        industry: 'Retail / E-Commerce',
        brief: 'Perform a full OWASP Top 10 penetration test against a deliberately vulnerable e-commerce application.',
        howTo: 'Set up OWASP Juice Shop as the target. Conduct structured assessment covering injection, broken auth, XSS, IDOR, and security misconfiguration. Write an executive-friendly pentest report.',
        tools: ['Burp Suite', 'OWASP ZAP', 'SQLmap', 'Kali Linux', 'Postman'],
        artifact: 'Full Penetration Testing Report with executive summary, technical findings, and CVSS scores.',
      },
      {
        title: 'Telecom Active Directory Hardening Project',
        industry: 'Telecommunications',
        brief: 'Harden an Active Directory environment representing a Nigerian telecoms company against Kerberoasting, Pass-the-Hash, and privilege escalation attacks.',
        howTo: 'Set up Windows Server AD lab. Use BloodHound to map attack paths. Implement GPO hardening, disable legacy protocols, enforce least privilege, and enable audit logging. Document all changes.',
        tools: ['Windows Server', 'BloodHound', 'PowerShell', 'Mimikatz (testing)', 'Snort'],
        artifact: 'AD Hardening Guide, BloodHound attack path remediation tree, and Group Policy export.',
      },
      {
        title: 'Oil and Gas SCADA Cybersecurity Assessment',
        industry: 'Oil and Gas',
        brief: 'Assess the cybersecurity posture of a simulated SCADA/OT environment representing a Nigerian oil production facility.',
        howTo: 'Build a simulated OT environment using Conpot ICS honeypot. Map the IT/OT boundary. Identify SCADA-specific vulnerabilities. Produce a risk matrix and segmentation recommendation.',
        tools: ['Conpot', 'Nmap', 'Wireshark', 'NIST SP 800-82', 'VirtualBox'],
        artifact: 'SCADA Security Assessment Report with IT/OT segmentation blueprint.',
      },
      {
        title: 'Ransomware Forensics Investigation Case',
        industry: 'Any Enterprise',
        brief: 'Conduct a full digital forensics investigation of a simulated ransomware attack on a fictional Nigerian company.',
        howTo: 'Create a Windows VM infected with a benign simulated ransomware script. Capture memory and disk images. Analyse with Volatility and Autopsy. Reconstruct the attack timeline and produce a DFIR report.',
        tools: ['FTK Imager', 'Autopsy', 'Volatility', 'YARA', 'VirtualBox'],
        artifact: 'DFIR Investigation Report with attack timeline and Indicator of Compromise list.',
      },
      {
        title: 'Government Ministry Zero Trust Architecture Design',
        industry: 'Government',
        brief: 'Design a Zero Trust Network Architecture for a fictional Nigerian government ministry with 500 employees.',
        howTo: 'Map the fictional ministry network topology. Apply NIST Zero Trust principles. Design IAM policies, micro-segmentation plan, MFA enforcement, and device trust verification. Build architecture diagram.',
        tools: ['Lucidchart / Draw.io', 'Tailscale', 'Okta (free tier)', 'WireGuard'],
        artifact: 'Zero Trust Implementation Blueprint: architecture diagram and 15-page design document.',
      },
      {
        title: 'Healthcare API Security Testing Suite',
        industry: 'Healthcare',
        brief: 'Test the security of a fictional Nigerian health records REST API against OWASP API Top 10 vulnerabilities.',
        howTo: 'Build an Express.js health records API with intentional vulnerabilities. Test with Postman and Burp Suite. Fix all vulnerabilities. Document the full process.',
        tools: ['Postman', 'Burp Suite', 'Express.js', 'Python', 'JWT.io'],
        artifact: 'API Security Test Suite on GitHub and API Security Assessment Report.',
      },
      {
        title: 'Real Estate Platform Data Privacy Compliance Audit',
        industry: 'Real Estate',
        brief: 'Conduct a data privacy and security audit of a fictional Nigerian real estate listing platform under NDPA 2023.',
        howTo: 'Map all data flows on the fictional platform. Assess against NDPA 2023 requirements. Identify gaps in consent management, data retention, and breach notification. Produce a compliance report.',
        tools: ['OWASP Testing Guide', 'NDPA 2023', 'Microsoft Word'],
        artifact: 'NDPA 2023 Data Privacy Compliance Audit Report with gap analysis and remediation plan.',
      },
    ],
    black: [
      {
        title: 'Autonomous Threat Intelligence Platform',
        industry: 'Fintech / Defence',
        brief: 'Build a fully automated threat intelligence aggregation and alerting platform ingesting from open-source threat feeds.',
        howTo: 'Integrate MISP or OpenCTI with live feeds (AlienVault OTX, Abuse.ch). Build a Python pipeline that enriches indicators, maps to MITRE ATT&CK, and sends real-time Slack/email alerts. Deploy on a cloud VPS.',
        tools: ['MISP / OpenCTI', 'Python', 'AlienVault OTX API', 'MITRE ATT&CK', 'Docker'],
        artifact: 'Deployed Threat Intelligence Platform with GitHub automation scripts and live demo.',
      },
      {
        title: 'National Grid SCADA Cyber Defence Architecture',
        industry: 'Energy / Government',
        brief: 'Design and simulate a full cyber defence architecture for a national power grid OT environment.',
        howTo: 'Build a layered OT/IT defence model using Conpot honeypots, IDS rules for SCADA protocols, network segmentation, and incident response playbooks. Present as a security architecture document.',
        tools: ['Conpot', 'Suricata', 'Wireshark', 'NIST SP 800-82', 'IEC 62443'],
        artifact: 'National Grid Cyber Defence Architecture document (30+ pages) with diagrams and IDS ruleset.',
      },
      {
        title: 'Banking Sector Red Team Engagement Report',
        industry: 'Banking / Fintech',
        brief: 'Conduct a simulated red team operation against a fictional Nigerian bank\'s infrastructure from reconnaissance to post-exploitation.',
        howTo: 'Plan and execute a structured red team engagement covering OSINT, phishing, initial access, lateral movement, and data exfiltration in a controlled lab. Document using the MITRE ATT&CK framework.',
        tools: ['Kali Linux', 'Metasploit', 'BloodHound', 'Cobalt Strike (community)', 'MITRE ATT&CK Navigator'],
        artifact: 'Full Red Team Engagement Report with MITRE ATT&CK heat map and executive brief.',
      },
      {
        title: 'Hospital Ransomware Resilience Framework',
        industry: 'Healthcare',
        brief: 'Build a comprehensive ransomware resilience framework for a Nigerian teaching hospital covering prevention, detection, response, and recovery.',
        howTo: 'Design backup architecture (3-2-1 rule). Build detection rules for ransomware precursors. Create tested incident response playbooks. Conduct a tabletop exercise and evaluate results.',
        tools: ['Wazuh', 'Veeam Backup (community)', 'YARA', 'Python', 'Microsoft Word'],
        artifact: 'Hospital Ransomware Resilience Framework, incident response playbooks, and tabletop exercise report.',
      },
      {
        title: 'Blockchain-Based Evidence Chain of Custody System',
        industry: 'Legal / Government',
        brief: 'Build a smart contract system recording digital evidence custody transfers on blockchain for tamper-proof chain of custody.',
        howTo: 'Write an Ethereum smart contract recording evidence ID, custodian, timestamp, and transfer events. Build a React front end for custody transfer logging. Deploy on Polygon testnet.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Polygon testnet', 'IPFS'],
        artifact: 'Deployed evidence chain of custody dApp with verified smart contract on Polygon testnet.',
      },
      {
        title: 'Telecom Zero Day Vulnerability Research Report',
        industry: 'Telecommunications',
        brief: 'Conduct structured vulnerability research on a widely used open-source telecom protocol implementation and produce a responsible disclosure report.',
        howTo: 'Select an open-source SIP/VoIP implementation (e.g. Asterisk). Fuzz input handlers. Document crashes and unexpected behaviours. Write a responsible disclosure report following CVD best practices.',
        tools: ['AFL++ (fuzzer)', 'Kali Linux', 'Wireshark', 'Python', 'GDB'],
        artifact: 'Vulnerability Research Report and responsible disclosure documentation.',
      },
      {
        title: 'AI-Powered Malware Detection Engine',
        industry: 'Technology / Enterprise',
        brief: 'Build a machine learning model that classifies executable files as malware or benign using static and behavioural features.',
        howTo: 'Collect PE file features from MalwareBazaar dataset. Engineer features (imports, entropy, section names). Train Random Forest and XGBoost classifiers. Deploy as a Flask API endpoint.',
        tools: ['Python', 'Scikit-learn', 'XGBoost', 'LIEF', 'Flask', 'Docker'],
        artifact: 'Deployed Malware Detection API on GitHub with model performance report (accuracy, F1, AUC-ROC).',
      },
      {
        title: 'Oil and Gas Pipeline IEC 62443 Cybersecurity Risk Assessment',
        industry: 'Oil and Gas',
        brief: 'Produce a full IEC 62443-aligned cybersecurity risk assessment for a fictional Nigerian crude oil pipeline SCADA system.',
        howTo: 'Map the fictional pipeline control system (PLCs, RTUs, HMI, historian). Apply IEC 62443 methodology. Identify zones and conduits. Score risks. Produce risk assessment with security level targets.',
        tools: ['IEC 62443', 'NIST RMF', 'Draw.io', 'Microsoft Excel'],
        artifact: 'Pipeline SCADA Cybersecurity Risk Assessment Report (IEC 62443 aligned, 30+ pages).',
      },
      {
        title: 'National Cybersecurity Policy Framework for an African Nation',
        industry: 'Government / Policy',
        brief: 'Draft a national-level cybersecurity policy framework for a fictional African nation aligned with AU and international best practices.',
        howTo: 'Research the African Union Malabo Convention, ITU Global Cybersecurity Agenda, and ECOWAS frameworks. Draft policy covering governance, critical infrastructure protection, incident response, and capacity building.',
        tools: ['AU Malabo Convention', 'ITU GCI', 'ECOWAS frameworks', 'Microsoft Word'],
        artifact: 'National Cybersecurity Policy Framework (40+ pages) with implementation roadmap.',
      },
      {
        title: 'Cybersecurity Startup Penetration Testing Service Package',
        industry: 'Innovation / Entrepreneurship',
        brief: 'Build a complete, market-ready penetration testing service package for a cybersecurity startup targeting Nigerian SMEs.',
        howTo: 'Design three service tiers. Create methodology documentation, client intake forms, legal agreement templates, sample pentest report templates, and a Nigerian market pricing model.',
        tools: ['LaTeX / Microsoft Word', 'OWASP Testing Guide', 'PTES methodology'],
        artifact: 'Complete Penetration Testing Service Package: methodology, legal templates, pricing, and sample report.',
      },
    ],
  },

  'data-analytics': {
    green: [
      {
        title: 'Nigerian FMCG Sales Performance Dashboard',
        industry: 'Retail / FMCG',
        brief: 'Build an interactive Power BI dashboard tracking sales, product categories, and regional revenue for a fictional Nigerian consumer goods company.',
        howTo: 'Create a realistic fictional dataset with 12 months of sales across 6 states. Clean in Power Query. Build KPI cards, bar charts, regional maps, and monthly trend lines in Power BI.',
        tools: ['Power BI Desktop', 'Excel', 'Power Query'],
        artifact: 'Published Power BI Dashboard with a 2-minute video walkthrough explaining business insights.',
      },
      {
        title: 'Hospital Patient Flow and Bed Occupancy Tracker',
        industry: 'Healthcare',
        brief: 'Analyse patient admission, discharge, and bed occupancy data for a fictional Nigerian hospital to identify efficiency bottlenecks.',
        howTo: 'Create a fictional hospital dataset. Calculate average length of stay, bed utilisation rate, and peak admission hours. Build a dashboard with daily, weekly, and monthly views.',
        tools: ['Power BI', 'Excel', 'Python (Pandas)'],
        artifact: 'Healthcare Operations Dashboard and 2-page management summary brief.',
      },
      {
        title: 'Nigerian Agricultural Commodity Price Analysis',
        industry: 'Agriculture',
        brief: 'Analyse price trends for three Nigerian staple crops (yam, cassava, maize) across market zones and seasons over three years.',
        howTo: 'Create a realistic fictional dataset. Clean and structure the data. Produce trend charts, seasonal decomposition, and regional price comparison. Identify price shock periods.',
        tools: ['Excel', 'Python (Pandas, Matplotlib)', 'Google Looker Studio'],
        artifact: 'Agricultural Price Analysis Report with interactive charts and key findings brief.',
      },
      {
        title: 'Government Budget Spending Transparency Dashboard',
        industry: 'Government',
        brief: 'Analyse a fictional Nigerian state government\'s budget versus actual expenditure across 5 ministries over 2 years.',
        howTo: 'Structure fictional budget data in Excel. Calculate variance between budgeted and actual spend per ministry. Identify overspend and underspend patterns. Build a public transparency dashboard.',
        tools: ['Excel', 'Power BI', 'Google Looker Studio'],
        artifact: 'Government Budget Transparency Dashboard and citizen-facing summary report.',
      },
      {
        title: 'University Student Academic Performance Analytics',
        industry: 'Education',
        brief: 'Analyse academic performance data for a fictional Nigerian university cohort of 500 students across 4 departments.',
        howTo: 'Create a fictional student dataset with grades, attendance, gender, department, and scholarship status. Analyse pass/fail rates, grade distributions, and attendance correlation with performance.',
        tools: ['Python (Pandas, Seaborn)', 'Excel', 'Power BI'],
        artifact: 'Student Performance Analytics Report with visualisations and departmental recommendations.',
      },
      {
        title: 'Lagos Ride-Hailing Trip Demand Analysis',
        industry: 'Transport / Innovation',
        brief: 'Analyse a fictional dataset of 10,000 ride-hailing trips across Lagos, Abuja, and Port Harcourt to identify demand patterns.',
        howTo: 'Create fictional trip data including pickup zone, time of day, distance, fare, and rating. Analyse peak hours, highest-demand zones, and revenue-per-driver metrics.',
        tools: ['Python (Pandas, Folium, Matplotlib)', 'Tableau Public'],
        artifact: 'Interactive city-level ride demand map and trip pattern analysis report.',
      },
      {
        title: 'Social Media Sentiment Analysis for a Nigerian Brand',
        industry: 'Marketing / Social',
        brief: 'Analyse Twitter/X data (simulated) for a Nigerian brand and measure public sentiment around a product launch.',
        howTo: 'Use a pre-collected dataset or simulate 1,000 posts. Apply VADER sentiment analysis. Categorise sentiment. Visualise trends over time and by topic.',
        tools: ['Python (NLTK, VADER, Matplotlib)', 'Tableau'],
        artifact: 'Brand Sentiment Dashboard and marketing recommendation report.',
      },
      {
        title: 'Oil Field Production Performance Dashboard',
        industry: 'Oil and Gas',
        brief: 'Build a production monitoring dashboard for a fictional Nigerian oil field tracking daily output, downtime, and efficiency metrics.',
        howTo: 'Create a fictional production dataset with daily barrels, uptime %, maintenance events, and field location. Build KPI cards and trend charts. Flag fields below target.',
        tools: ['Power BI', 'Excel', 'Python (optional)'],
        artifact: 'Oil Field Production Dashboard with monthly performance summary and anomaly flags.',
      },
      {
        title: 'Port Harcourt Real Estate Rental Market Analysis',
        industry: 'Real Estate',
        brief: 'Analyse rental price trends across Port Harcourt neighbourhoods using a fictional or scraped dataset.',
        howTo: 'Create or collect a dataset of 500 rental listings with price, location, size, and property type. Calculate price per square metre by neighbourhood. Map affordability by zone.',
        tools: ['Python (Pandas, Folium)', 'Excel', 'Tableau Public'],
        artifact: 'Port Harcourt Rental Market Analysis Report with interactive neighbourhood map.',
      },
      {
        title: 'Nigerian Food Security and Malnutrition Dashboard',
        industry: 'Social / Humanitarian',
        brief: 'Visualise food security indicators across Nigerian states using publicly available data from NBS or UNICEF.',
        howTo: 'Download or simulate food security data (stunting rates, caloric intake, food price inflation). Build a state-by-state comparison dashboard. Identify the three most food-insecure states.',
        tools: ['Power BI', 'Python (Pandas)', 'Excel', 'NBS/UNICEF data'],
        artifact: 'Food Security Dashboard and evidence-based policy brief for 3 target states.',
      },
    ],
    blue: [
      {
        title: 'Fintech Customer Churn Prediction Model',
        industry: 'Fintech / Banking',
        brief: 'Build a machine learning model predicting which customers of a fictional Nigerian digital bank are most likely to churn within 30 days.',
        howTo: 'Create a dataset of 5,000 fictional customer records. Engineer churn-risk features. Train Logistic Regression and Random Forest models. Evaluate with confusion matrix and ROC curve. Build a Tableau dashboard.',
        tools: ['Python (Pandas, Scikit-learn, Matplotlib)', 'Jupyter Notebook', 'Tableau'],
        artifact: 'Churn model notebook on GitHub, Tableau dashboard, and business recommendation report.',
      },
      {
        title: 'Healthcare Drug Supply Chain ETL Pipeline',
        industry: 'Healthcare',
        brief: 'Build an automated ETL pipeline ingesting fictional hospital drug supply data, transforming it, and loading to a structured database for reporting.',
        howTo: 'Create fictional CSV files of daily drug orders, inventory levels, and supplier deliveries. Write Python ETL scripts. Load to PostgreSQL. Schedule with Apache Airflow. Build Metabase dashboard.',
        tools: ['Python', 'PostgreSQL', 'Apache Airflow', 'Metabase'],
        artifact: 'GitHub ETL repository with SQL schema, Airflow DAG, and live reporting dashboard.',
      },
      {
        title: 'Nigerian Crop Yield Prediction Model',
        industry: 'Agriculture',
        brief: 'Build a regression model predicting maize/yam yield based on rainfall, temperature, fertiliser use, and soil type for Nigerian farming zones.',
        howTo: 'Source or simulate 3 years of farm data across 6 Nigerian states. Clean and engineer features. Train and compare Linear Regression, Ridge, and XGBoost models. Map predictions by zone.',
        tools: ['Python (Scikit-learn, XGBoost, Folium)', 'Jupyter', 'Streamlit'],
        artifact: 'Deployed Streamlit crop yield prediction app and model performance report.',
      },
      {
        title: 'Oil Well Production Anomaly Detection System',
        industry: 'Oil and Gas',
        brief: 'Build an anomaly detection system flagging unusual drops or spikes in oil well production data using statistical and ML methods.',
        howTo: 'Create a fictional time-series of daily output for 10 wells over 2 years. Apply Z-score and Isolation Forest anomaly detection. Visualise annotated anomalies. Build an alert system.',
        tools: ['Python (Pandas, Scikit-learn, Plotly)', 'Streamlit', 'Prophet'],
        artifact: 'Deployed anomaly detection dashboard on Streamlit Cloud and findings report.',
      },
      {
        title: 'E-Commerce A/B Test Statistical Analysis',
        industry: 'Retail / E-Commerce',
        brief: 'Conduct a rigorous A/B test analysis for a fictional Nigerian e-commerce site that tested two product page designs.',
        howTo: 'Simulate an A/B experiment dataset with control and treatment groups. Apply t-tests, chi-square tests, and Bayesian analysis. Write a decision report with confidence intervals.',
        tools: ['Python (SciPy, Statsmodels, Pingouin)', 'Jupyter'],
        artifact: 'A/B Test Statistical Decision Report and visualised results dashboard.',
      },
      {
        title: 'Secondary School Dropout Early Warning System',
        industry: 'Education',
        brief: 'Build a predictive model identifying secondary school students at risk of dropping out based on attendance, grades, and socioeconomic indicators.',
        howTo: 'Create a fictional dataset of 2,000 students. Engineer dropout risk features. Train a classification model. Build an early warning dashboard for school administrators.',
        tools: ['Python (Scikit-learn, Pandas)', 'Power BI', 'Streamlit'],
        artifact: 'Early Warning System prototype with model accuracy report and administrator dashboard.',
      },
      {
        title: 'Nigerian State Government Revenue Forecasting Model',
        industry: 'Government',
        brief: 'Build a time-series forecasting model projecting a fictional Nigerian state\'s tax revenue for the next 12 months.',
        howTo: 'Create 5 years of monthly revenue data by tax category. Apply ARIMA and Prophet forecasting. Compare model accuracy. Present projections with confidence intervals.',
        tools: ['Python (Prophet, Statsmodels, Pandas)', 'Matplotlib', 'Power BI'],
        artifact: 'Revenue Forecasting Report with 12-month projection chart and model validation metrics.',
      },
      {
        title: 'Urban Social Housing Needs Assessment Dashboard',
        industry: 'Government / Social',
        brief: 'Analyse housing deficit data across Nigerian states and build a prioritisation dashboard for social housing investment.',
        howTo: 'Use NBS data or simulate population density, household income, and shelter quality. Calculate housing deficit per state. Score states by urgency. Build a decision-support dashboard.',
        tools: ['Python', 'Power BI', 'Folium', 'Excel'],
        artifact: 'Social Housing Needs Dashboard and investment prioritisation brief.',
      },
      {
        title: 'SaaS Business Unit Economics Tracker',
        industry: 'Innovation / Technology',
        brief: 'Build a full SaaS metrics tracking system computing MRR, ARR, CAC, LTV, churn rate, and Net Revenue Retention.',
        howTo: 'Create a fictional SaaS company\'s 24-month subscriber dataset. Write SQL queries to compute all unit economics metrics. Build a dashboard with month-over-month trends.',
        tools: ['PostgreSQL', 'dbt', 'Metabase / Power BI', 'Python'],
        artifact: 'dbt project on GitHub, live SaaS metrics dashboard, and 6-month growth analysis report.',
      },
      {
        title: 'Niger Delta Environmental Pollution and Health Analytics',
        industry: 'Environment / Health',
        brief: 'Analyse the relationship between air pollution levels and respiratory disease rates across Niger Delta communities.',
        howTo: 'Compile air quality (PM2.5, SO2) data and hospital admission rates for 5 fictional communities. Apply correlation analysis and regression. Visualise spatial pollution-health overlap.',
        tools: ['Python (Pandas, Seaborn, Folium)', 'Tableau'],
        artifact: 'Environmental Health Analysis Report with interactive community map and policy brief.',
      },
    ],
    black: [
      {
        title: 'Real-Time Banking Fraud Detection Pipeline',
        industry: 'Fintech / Banking',
        brief: 'Build an end-to-end real-time fraud detection ML pipeline processing transaction data and flagging anomalies within milliseconds.',
        howTo: 'Train XGBoost on a fraud dataset. Handle class imbalance with SMOTE. Containerise with Docker. Deploy as a FastAPI endpoint. Monitor with MLflow.',
        tools: ['Python', 'XGBoost', 'FastAPI', 'Docker', 'MLflow', 'Kafka (optional)'],
        artifact: 'Containerised Fraud Detection API on GitHub with Swagger docs, model card, and performance report.',
      },
      {
        title: 'National Electricity Grid Digital Twin',
        industry: 'Energy / Government',
        brief: 'Build a data-driven digital twin of a fictional Nigerian state power grid simulating demand forecasting, outage prediction, and load balancing.',
        howTo: 'Create 2 years of hourly demand, generation, and outage time-series data. Build forecasting models (Prophet, LSTM). Create a Streamlit dashboard simulating real-time grid status.',
        tools: ['Python (Prophet, TensorFlow/Keras, Streamlit)', 'Pandas', 'Plotly'],
        artifact: 'Deployed Digital Twin Dashboard on Streamlit Cloud with full documentation.',
      },
      {
        title: 'Hospital Readmission Prediction and Bed Optimisation System',
        industry: 'Healthcare',
        brief: 'Build an ML system predicting 30-day hospital readmissions and optimising bed allocation in a fictional teaching hospital.',
        howTo: 'Create a dataset of 10,000 fictional patient admissions. Train a Gradient Boosting model. Build a bed allocation optimisation algorithm. Deploy as a hospital dashboard.',
        tools: ['Python (Scikit-learn, LightGBM, OR-Tools, Streamlit)'],
        artifact: 'Hospital Intelligence Dashboard on Streamlit, model performance report, and optimisation case study.',
      },
      {
        title: 'Agricultural Commodity Trading Signal Engine',
        industry: 'Agriculture / Fintech',
        brief: 'Build a data pipeline and ML system generating buy/sell signals for Nigerian agricultural commodities based on price patterns and weather data.',
        howTo: 'Simulate 5-year price data for 4 commodities. Integrate weather API. Engineer technical indicators (moving averages, RSI). Train a price direction classifier. Deploy as a dashboard.',
        tools: ['Python (TA-Lib, Scikit-learn, Streamlit)', 'OpenWeatherMap API', 'Plotly'],
        artifact: 'Commodity Trading Signal Dashboard with backtesting results and strategy documentation.',
      },
      {
        title: 'Oil and Gas Asset Lifecycle Cost Analytics Platform',
        industry: 'Oil and Gas',
        brief: 'Build a full-stack data platform modelling the total cost of ownership of oil field assets across their 20-year lifecycle.',
        howTo: 'Model a fictional oil field with CAPEX, OPEX, production revenue, and decommissioning costs. Build a Monte Carlo simulation for cost uncertainty. Create an executive dashboard with scenario analysis.',
        tools: ['Python (NumPy, SciPy Monte Carlo)', 'Power BI', 'Excel', 'dbt'],
        artifact: 'Asset Lifecycle Cost Analytics Platform with Monte Carlo simulation and executive scenario report.',
      },
      {
        title: 'E-Commerce Personalisation Recommendation Engine',
        industry: 'Retail / E-Commerce',
        brief: 'Build a production-ready product recommendation engine for a fictional Nigerian e-commerce platform.',
        howTo: 'Create 100,000 fictional user-product interactions. Implement collaborative filtering (matrix factorisation) and content-based filtering. Combine into a hybrid model. Deploy as a FastAPI endpoint.',
        tools: ['Python (Surprise, LightFM, FastAPI, Docker)', 'PostgreSQL'],
        artifact: 'Deployed Recommendation Engine API on GitHub with evaluation metrics and A/B test design.',
      },
      {
        title: 'Urban Transport Data Intelligence Platform',
        industry: 'Government / Transport',
        brief: 'Build an integrated platform analysing urban traffic patterns, public transport gaps, and road incident hotspots for a fictional Nigerian city.',
        howTo: 'Simulate GPS trajectory data, bus route ridership, and road incident records. Build a multi-layer analytical dashboard with demand mapping, gap analysis, and incident heatmaps.',
        tools: ['Python (Pandas, Folium, GeoPandas)', 'Streamlit', 'PostgreSQL'],
        artifact: 'Urban Transport Intelligence Platform with interactive city map and investment recommendation brief.',
      },
      {
        title: 'Corporate ESG and GHG Emissions Reporting Tool',
        industry: 'Finance / Environment',
        brief: 'Build a data tool helping Nigerian corporations calculate, track, and report Scope 1 and Scope 2 greenhouse gas emissions aligned with GHG Protocol.',
        howTo: 'Define emission factors for the Nigerian energy mix. Build an input system for energy consumption by source. Calculate Scope 1 and 2 totals. Generate a GHG Protocol-aligned report.',
        tools: ['Python', 'Streamlit', 'Pandas', 'Excel', 'GHG Protocol methodology'],
        artifact: 'Deployed ESG Emission Calculator app and sample corporate GHG inventory report.',
      },
      {
        title: 'MLOps Platform for Continuous Model Lifecycle Management',
        industry: 'Technology / Any',
        brief: 'Build a production-grade MLOps infrastructure covering training, versioning, deployment, monitoring, and automated retraining.',
        howTo: 'Train a baseline model. Set up MLflow for tracking. Use DVC for data versioning. Create GitHub Actions CI/CD for retraining. Monitor with Evidently AI for drift detection.',
        tools: ['Python', 'MLflow', 'DVC', 'GitHub Actions', 'Docker', 'Evidently AI', 'BentoML'],
        artifact: 'Full MLOps pipeline on GitHub with architecture diagram, drift detection demo, and retraining trigger report.',
      },
      {
        title: 'Financial Inclusion Index for Nigerian States',
        industry: 'Fintech / Social',
        brief: 'Build a composite financial inclusion index ranking Nigerian states by access to banking, digital payments, credit, and insurance.',
        howTo: 'Collect or simulate state-level data on bank account ownership, POS density, mobile money usage, and microfinance penetration. Apply PCA for index construction. Rank states and map findings.',
        tools: ['Python (Scikit-learn PCA, Pandas)', 'Power BI', 'Folium'],
        artifact: 'Financial Inclusion Index Report with state ranking dashboard and policy intervention brief.',
      },
    ],
  },

  blockchain: {
    green: [
      {
        title: 'Crypto Portfolio Tracker Web App',
        industry: 'Fintech / Personal',
        brief: 'Build a personal crypto portfolio tracker displaying holdings, live prices, and transaction history for multiple wallets.',
        howTo: 'Connect to CoinGecko API for live prices. Allow user to input wallet addresses and balances. Display portfolio value, allocation pie chart, and 30-day performance. Deploy as a React app.',
        tools: ['React.js', 'CoinGecko API', 'Chart.js', 'TailwindCSS', 'Vercel'],
        artifact: 'Deployed portfolio tracker app on Vercel with GitHub repository.',
      },
      {
        title: 'School Rewards ERC-20 Token',
        industry: 'Education',
        brief: 'Create and deploy an ERC-20 token that a fictional school can use to reward students for academic achievements.',
        howTo: 'Write an ERC-20 Solidity contract with mint, transfer, and burn functions. Add role-based admin minting. Deploy on Sepolia testnet. Verify source code on Etherscan.',
        tools: ['Solidity', 'Remix IDE', 'MetaMask', 'Sepolia testnet', 'Etherscan'],
        artifact: 'Verified ERC-20 contract on Etherscan, GitHub source, and school token design document.',
      },
      {
        title: 'NFT Minting Platform for Nigerian Digital Artists',
        industry: 'Creative / Arts',
        brief: 'Build a simple NFT minting dApp allowing digital artists to mint artwork as ERC-721 tokens on a testnet.',
        howTo: 'Write an ERC-721 Solidity contract. Store metadata on IPFS via Pinata. Build a React front end with MetaMask connection and minting button. Deploy on Polygon Mumbai testnet.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Pinata (IPFS)', 'MetaMask', 'Polygon Mumbai'],
        artifact: 'Live NFT minting dApp on Vercel with verified contract on Polygonscan.',
      },
      {
        title: 'Blockchain Certificate Verification System',
        industry: 'Education',
        brief: 'Build a system where a fictional institution issues graduation certificates on-chain and anyone can verify authenticity by entering a code.',
        howTo: 'Write a Solidity contract storing certificate hashes. Build an admin panel to issue certificates and a public verification page for users to check authenticity.',
        tools: ['Solidity', 'Remix', 'React.js', 'Ethers.js', 'Sepolia testnet'],
        artifact: 'Live certificate verification dApp on Vercel and GitHub repository.',
      },
      {
        title: 'Farmers Cooperative Token Treasury',
        industry: 'Agriculture',
        brief: 'Build a token-based treasury system for a fictional Nigerian farmers cooperative distributing profit-sharing tokens.',
        howTo: 'Deploy an ERC-20 token. Write a distribution contract sending tokens proportionally to registered farmer addresses. Build a tracker showing each farmer\'s token balance.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'MetaMask', 'Sepolia testnet'],
        artifact: 'Token distribution dApp on Vercel and cooperative token design document.',
      },
      {
        title: 'Patient Health Record Consent dApp',
        industry: 'Healthcare',
        brief: 'Build a prototype where patients control who accesses their health records using blockchain-based consent flags.',
        howTo: 'Write a Solidity contract where each patient address grants or revokes read permission to doctor addresses. Build a simple React interface for patients and doctors.',
        tools: ['Solidity', 'Remix', 'React.js', 'Ethers.js', 'MetaMask', 'Sepolia testnet'],
        artifact: 'Patient consent dApp on Vercel and GitHub repository with security analysis.',
      },
      {
        title: 'Property Title Registry Prototype',
        industry: 'Real Estate',
        brief: 'Build a blockchain prototype recording property title transfers to eliminate paper-based fraud risks common in Nigerian real estate.',
        howTo: 'Write a Solidity contract storing property ID, current owner, and transfer history. Build a search interface to look up any property\'s ownership history.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Ethers.js', 'Sepolia testnet'],
        artifact: 'Property registry dApp on Vercel and fraud prevention design document.',
      },
      {
        title: 'Ajo/Esusu Rotating Savings Smart Contract',
        industry: 'Fintech / Social',
        brief: 'Build a smart contract automating the Nigerian traditional rotating savings group (Ajo/Esusu) with transparent fund management.',
        howTo: 'Write a Solidity contract where members contribute ETH in cycles and receive the pooled amount in rotation. Handle missed contributions with penalties. Build a member dashboard.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Ethers.js', 'MetaMask', 'Sepolia testnet'],
        artifact: 'Ajo/Esusu savings dApp on Vercel and economic design document.',
      },
      {
        title: 'Farm-to-Shelf Food Safety Tracker',
        industry: 'Agriculture / Retail',
        brief: 'Build a blockchain traceability system tracking a food product (e.g. palm oil) from farm to retail shelf.',
        howTo: 'Write a Solidity contract recording each stage: farm harvest, processing, packaging, distributor, and retail. Build a consumer-facing QR scan verification page.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'QR code library', 'Polygon testnet'],
        artifact: 'Food traceability dApp on Vercel and product journey documentation.',
      },
      {
        title: 'Multi-Network Crypto Wallet Dashboard',
        industry: 'Innovation / Web3',
        brief: 'Build a Web3 app connecting to MetaMask and displaying ETH and ERC-20 token balances across multiple testnets.',
        howTo: 'Implement wallet connect with Wagmi/RainbowKit. Query on-chain balances via Ethers.js. Display native ETH and ERC-20 balances with live USD conversion from CoinGecko.',
        tools: ['React.js', 'Wagmi', 'RainbowKit', 'Ethers.js', 'CoinGecko API', 'Vercel'],
        artifact: 'Deployed multi-network wallet dashboard on Vercel and GitHub repository.',
      },
    ],
    blue: [
      {
        title: 'DeFi Bill Payment Gateway for Nigerian Services',
        industry: 'Fintech',
        brief: 'Build a dApp allowing users to pay electricity bills and airtime top-ups using stablecoins on a testnet.',
        howTo: 'Integrate with a fictional billing API. Write an escrow smart contract holding payment until service provider confirms delivery. Build a React UI for wallet connection, service selection, and payment.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Wagmi', 'Viem', 'Sepolia testnet'],
        artifact: 'Deployed DeFi payment dApp on Vercel with tested escrow contract on GitHub.',
      },
      {
        title: 'NFT Marketplace with Artist Royalty System',
        industry: 'Creative / Arts',
        brief: 'Build a full NFT marketplace where artists list, buy, and sell digital art with automatic royalty payments on secondary sales.',
        howTo: 'Write ERC-721 contracts with EIP-2981 royalty standard. Build a marketplace contract for listing and buying. Build React frontend with IPFS metadata. Deploy on Polygon Mumbai.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Pinata (IPFS)', 'TailwindCSS', 'Polygon Mumbai'],
        artifact: 'Live NFT Marketplace dApp on Vercel with verified contracts on Polygonscan.',
      },
      {
        title: 'Decentralised Crowdfunding for Nigerian Startups',
        industry: 'Innovation / Entrepreneurship',
        brief: 'Build a Web3 Kickstarter allowing Nigerian entrepreneurs to raise transparent, fraud-resistant funding from global supporters.',
        howTo: 'Write a campaign contract with milestone-based fund release. Implement refund mechanism if campaign fails. Build a React UI showing live funding progress. Deploy on Sepolia testnet.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Ethers.js', 'MetaMask', 'Vercel'],
        artifact: 'Live crowdfunding dApp on Vercel with full GitHub repository and test coverage report.',
      },
      {
        title: 'Oil Production Revenue Sharing Smart Contract',
        industry: 'Oil and Gas',
        brief: 'Build a smart contract automatically distributing oil production revenue proportionally to investors, operators, and host communities.',
        howTo: 'Write a Solidity distribution contract with configurable percentage splits. Allow admin to deposit revenue and trigger distribution. Build an investor dashboard showing cumulative earnings.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Ethers.js', 'Sepolia testnet'],
        artifact: 'Revenue sharing dApp on Vercel, tested contract on GitHub, and mechanism design document.',
      },
      {
        title: 'Blockchain Agricultural Microfinance Platform',
        industry: 'Agriculture / Fintech',
        brief: 'Build a DeFi lending platform for Nigerian smallholder farmers using tokenised crop as collateral.',
        howTo: 'Write a lending contract where farmers deposit a tokenised farm asset as collateral and receive a stablecoin loan. Implement liquidation logic. Build farmer and lender dashboards.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Chainlink Price Feeds', 'Sepolia testnet'],
        artifact: 'Agricultural lending dApp on Vercel, contracts on GitHub, and economic model document.',
      },
      {
        title: 'Community Development Fund DAO',
        industry: 'Government / Social',
        brief: 'Build a decentralised governance platform where Niger Delta community members vote on how development funds are allocated.',
        howTo: 'Write an ERC-20 governance token. Implement OpenZeppelin Governor contract for proposal creation and on-chain voting. Build a React governance interface with active proposals and vote tallies.',
        tools: ['Solidity', 'OpenZeppelin Governor', 'Hardhat', 'React.js', 'Sepolia testnet'],
        artifact: 'Working DAO governance dApp on Vercel and governance token design document.',
      },
      {
        title: 'NGO Multi-Signature Treasury Wallet',
        industry: 'Social / Non-Profit',
        brief: 'Build a multi-signature wallet for an NGO requiring 3-of-5 board member approvals before executing treasury transactions.',
        howTo: 'Write a multi-sig Solidity contract with transaction queuing and approval logic. Build a React dashboard where signers view, approve, and execute pending transactions.',
        tools: ['Solidity', 'Foundry', 'React.js', 'Ethers.js', 'Sepolia testnet'],
        artifact: 'Multi-sig treasury dApp on Vercel, contracts on GitHub, and NGO governance policy document.',
      },
      {
        title: 'Pharmaceutical Supply Chain Anti-Counterfeit Tracker',
        industry: 'Healthcare',
        brief: 'Build a pharmaceutical supply chain tracker recording each drug\'s journey from manufacturer to patient, preventing counterfeiting.',
        howTo: 'Write a Solidity contract with multi-role access (manufacturer, distributor, pharmacy, hospital). Record each transfer event. Build a QR scan verification page for patients.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'QR code library', 'Polygon testnet'],
        artifact: 'Drug supply chain dApp on Vercel and pharmaceutical fraud prevention case study.',
      },
      {
        title: 'DeFi Staking and Yield Reward Protocol',
        industry: 'Fintech / DeFi',
        brief: 'Build a DeFi staking protocol where users lock ERC-20 tokens and earn time-weighted yield rewards.',
        howTo: 'Write a staking contract with ERC-20 deposit, reward accumulation based on time staked, and secure withdrawal. Implement re-entrancy protection. Build a staking dashboard.',
        tools: ['Solidity', 'Foundry', 'React.js', 'TailwindCSS', 'Sepolia testnet'],
        artifact: 'Deployed staking protocol dApp on Vercel and contracts with test suite on GitHub.',
      },
      {
        title: 'African Diaspora Cross-Border Remittance dApp',
        industry: 'Fintech / Social',
        brief: 'Build a stablecoin-based cross-border remittance interface allowing diaspora Africans to send money home with minimal fees.',
        howTo: 'Implement USDC transfer interface with recipient address and NGN equivalent display using CoinGecko rates. Add transaction history panel. Demonstrate fee comparison vs traditional wire.',
        tools: ['React.js', 'Wagmi', 'Ethers.js', 'CoinGecko API', 'USDC on testnet', 'Vercel'],
        artifact: 'Deployed remittance dApp on Vercel and fee comparison analysis report (Web3 vs bank wire).',
      },
    ],
    black: [
      {
        title: 'Production-Grade DeFi Protocol with Security Audit',
        industry: 'Fintech / DeFi',
        brief: 'Build, test, and self-audit a production-grade DeFi protocol following Consensys and Trail of Bits security patterns.',
        howTo: 'Design the protocol architecture. Write Solidity contracts with Foundry. Achieve 95%+ test coverage. Run Slither and Mythril static analysis. Produce a smart contract audit report.',
        tools: ['Solidity', 'Foundry', 'Slither', 'Mythril', 'Echidna (fuzzing)', 'GitHub'],
        artifact: 'Production-ready protocol repository with full audit report and security remediation documentation.',
      },
      {
        title: 'Decentralised Identity for Nigerian Financial Inclusion',
        industry: 'Fintech / Social',
        brief: 'Build a decentralised identity system allowing unbanked Nigerians to create a verifiable digital identity for accessing financial services.',
        howTo: 'Implement W3C DID standard using Polygon ID or Ceramic Network. Allow users to create a DID and attach verifiable credentials. Build a financial service demo accepting the DID.',
        tools: ['Solidity', 'Polygon ID', 'React.js', 'Next.js', 'Ceramic Network'],
        artifact: 'Working DID portal dApp on Vercel and financial inclusion impact assessment document.',
      },
      {
        title: 'On-Chain Carbon Credit Marketplace',
        industry: 'Environment / Finance',
        brief: 'Build a blockchain marketplace for trading verified carbon credits integrated with real-world carbon standard data.',
        howTo: 'Write ERC-1155 tokens representing carbon credit batches. Build a marketplace contract for listing and trading. Integrate a fictional verification oracle. Record all credit retirements on-chain.',
        tools: ['Solidity', 'ERC-1155', 'Hardhat', 'React.js', 'Chainlink Oracle', 'Polygon testnet'],
        artifact: 'Carbon credit marketplace dApp on Vercel and carbon market mechanism design paper.',
      },
      {
        title: 'Oil and Gas Production Sharing Contract System',
        industry: 'Oil and Gas',
        brief: 'Build a smart contract system managing oil and gas joint venture production sharing contracts and royalty payments.',
        howTo: 'Model a simplified PSC in Solidity: cost recovery, profit oil split, and royalty payment logic. Build an operator and government ministry dashboard.',
        tools: ['Solidity', 'Foundry', 'React.js', 'Ethers.js', 'Polygon testnet'],
        artifact: 'PSC smart contract system on GitHub and oil and gas contract mechanism design document.',
      },
      {
        title: 'Blockchain-Based National Land Registry',
        industry: 'Government / Real Estate',
        brief: 'Design and build a full land title registry on blockchain addressing Nigeria\'s endemic land fraud problem.',
        howTo: 'Model the Nigerian Certificate of Occupancy as an NFT. Build admin functions for LGEA registration, title transfer, and encumbrance recording. Implement a dispute resolution mechanism.',
        tools: ['Solidity', 'ERC-721', 'Hardhat', 'React.js', 'Ethers.js', 'Polygon testnet'],
        artifact: 'Land registry dApp on Vercel, full system design document, and government pitch deck.',
      },
      {
        title: 'Agricultural Real World Asset Tokenisation Platform',
        industry: 'Agriculture / Finance',
        brief: 'Build an RWA tokenisation platform representing fractional ownership of Nigerian farm output as tradeable tokens.',
        howTo: 'Design a farm token standard representing 1 kg of a specific crop. Build minting (backed by fictional warehouse receipt), trading, and redemption contracts. Create an investor dashboard.',
        tools: ['Solidity', 'ERC-20', 'Hardhat', 'React.js', 'Chainlink Price Feed', 'Polygon testnet'],
        artifact: 'Farm tokenisation dApp on Vercel and RWA design whitepaper (5+ pages).',
      },
      {
        title: 'Optimistic Rollup Architecture Prototype',
        industry: 'Technology / Innovation',
        brief: 'Build an educational prototype demonstrating core concepts of an optimistic rollup: transaction batching, state commitment, and fraud proof.',
        howTo: 'Implement a simplified rollup sequencer in TypeScript that batches transactions, commits state roots to a Solidity rollup contract, and processes a fraud proof challenge. Document the architecture.',
        tools: ['Solidity', 'TypeScript', 'Hardhat', 'Ethers.js', 'Merkle tree library'],
        artifact: 'Rollup prototype repository on GitHub with architecture explainer and demo video.',
      },
      {
        title: 'Healthcare HMO Insurance Claims Automation',
        industry: 'Healthcare / Fintech',
        brief: 'Build a smart contract system automating Nigerian HMO insurance claim submissions, approvals, and payments.',
        howTo: 'Model the claim lifecycle in Solidity: patient submits claim, HMO approves or disputes, payment auto-releases on approval. Implement a dispute resolution step. Build patient and HMO dashboards.',
        tools: ['Solidity', 'Foundry', 'React.js', 'Ethers.js', 'Polygon testnet'],
        artifact: 'HMO claims dApp on Vercel, contracts on GitHub, and healthcare insurance reform paper.',
      },
      {
        title: 'Cross-Chain EVM Token Bridge',
        industry: 'Technology / Fintech',
        brief: 'Build a simplified cross-chain token bridge allowing ERC-20 tokens to move between two EVM testnets.',
        howTo: 'Implement lock-and-mint architecture: lock tokens on source chain, emit event, relayer mints on destination chain. Build a bridge interface. Implement replay protection and nonce management.',
        tools: ['Solidity', 'Hardhat', 'Ethers.js', 'Chainlink CCIP or LayerZero API', 'React.js'],
        artifact: 'Cross-chain bridge on GitHub with architecture diagram, security analysis, and demo video.',
      },
      {
        title: 'DeFi Startup: Investor-Ready Product Package',
        industry: 'Innovation / Entrepreneurship',
        brief: 'Design a complete investor-ready DeFi product including tokenomics, smart contract architecture, go-to-market strategy, and a working prototype.',
        howTo: 'Define the product (DEX, lending, RWA, or insurance). Design tokenomics model. Write core smart contracts. Build a landing page. Prepare a 10-slide pitch deck with financial projections.',
        tools: ['Solidity', 'Hardhat', 'React.js', 'Canva (deck)', 'Excel (tokenomics)'],
        artifact: 'Working prototype on Vercel, investor pitch deck, tokenomics paper, and contract repository.',
      },
    ],
  },

  'artificial-intelligence': {
    green: [
      {
        title: 'AI Customer Support Chatbot for a Nigerian Brand',
        industry: 'Retail / Fintech',
        brief: 'Build an AI-powered customer support chatbot for a fictional Nigerian e-commerce store answering product, order, and returns questions.',
        howTo: 'Use the OpenAI API or Mistral (free tier). Write a system prompt defining the fictional brand\'s policies. Build a Streamlit chat interface. Log conversation turns.',
        tools: ['Python', 'OpenAI API or Mistral', 'Streamlit', 'python-dotenv'],
        artifact: 'Deployed Streamlit chatbot on Streamlit Cloud with GitHub repository.',
      },
      {
        title: 'AI CV Screener for the Nigerian Job Market',
        industry: 'Human Resources',
        brief: 'Build a tool screening CVs against a job description and scoring each candidate\'s match using NLP.',
        howTo: 'Use SpaCy or Sentence-Transformers to compute similarity between job description text and CV text. Build a Streamlit interface where HR uploads a JD and multiple CVs. Display ranked candidates.',
        tools: ['Python', 'SpaCy', 'Sentence-Transformers', 'Streamlit', 'PyPDF2'],
        artifact: 'Deployed resume screening app on Streamlit Cloud with matching accuracy demonstration.',
      },
      {
        title: 'Crop Disease Identifier from Smartphone Photos',
        industry: 'Agriculture',
        brief: 'Build an image classification model identifying common Nigerian crop diseases (cassava mosaic, maize streak) from a smartphone photo.',
        howTo: 'Use the Kaggle PlantVillage dataset. Fine-tune a MobileNet model for target crop diseases. Build a Gradio interface where farmers upload a photo and get a diagnosis.',
        tools: ['Python', 'TensorFlow/Keras', 'MobileNet', 'Gradio', 'Google Colab'],
        artifact: 'Deployed crop disease identifier on Hugging Face Spaces and model performance report.',
      },
      {
        title: 'Nigerian News Article AI Summariser',
        industry: 'Media / Social',
        brief: 'Build a tool summarising long Nigerian news articles into 3-bullet executive summaries using an LLM.',
        howTo: 'Use an LLM API (OpenAI or Cohere) to summarise pasted article text. Build a Streamlit interface where users paste a URL or article text and receive a structured summary with a sentiment label.',
        tools: ['Python', 'OpenAI API or Cohere', 'BeautifulSoup (URL parsing)', 'Streamlit'],
        artifact: 'Deployed news summariser on Streamlit Cloud with a 10-article demonstration report.',
      },
      {
        title: 'Student Grade Pass/Fail Prediction Model',
        industry: 'Education',
        brief: 'Build an ML model predicting whether a student will pass or fail based on attendance, assignments, and test scores.',
        howTo: 'Create a fictional dataset of 500 students. Train a Logistic Regression and Decision Tree model. Build a simple Streamlit teacher dashboard for class-level risk monitoring.',
        tools: ['Python (Pandas, Scikit-learn, Streamlit)', 'Jupyter Notebook'],
        artifact: 'Deployed student prediction app on Streamlit Cloud and model interpretation report.',
      },
      {
        title: 'AI Personal Finance and Budget Advisor',
        industry: 'Fintech / Personal',
        brief: 'Build a personal finance AI assistant that categorises expenses, identifies spending patterns, and gives budget recommendations.',
        howTo: 'Build a Streamlit app where users upload a bank statement CSV. Use rule-based NLP to categorise transactions. Calculate spending by category. Use an LLM to generate personalised budget advice.',
        tools: ['Python', 'Pandas', 'OpenAI API', 'Streamlit', 'Matplotlib'],
        artifact: 'Deployed AI expense tracker on Streamlit Cloud with a sample budget advisory report.',
      },
      {
        title: 'Hospital Triage Priority Classifier',
        industry: 'Healthcare',
        brief: 'Build an ML model triaging incoming hospital patients by urgency level based on reported symptoms.',
        howTo: 'Create a fictional dataset of 1,000 patient intake forms with symptoms, vital signs, and triage level. Train Decision Tree and Random Forest classifiers. Build a nurse-facing Streamlit interface.',
        tools: ['Python (Scikit-learn, Pandas, Streamlit)', 'Jupyter Notebook'],
        artifact: 'Deployed hospital triage app on Streamlit Cloud and clinical validation report.',
      },
      {
        title: 'Nigerian Brand Social Media Sentiment Dashboard',
        industry: 'Marketing / Social',
        brief: 'Build a simulated real-time sentiment dashboard monitoring public opinion about a Nigerian brand from social posts.',
        howTo: 'Simulate 500 posts about a fictional Nigerian brand. Apply VADER sentiment analysis. Build a Streamlit dashboard with sentiment trend line, word cloud, and alert for sudden negative spikes.',
        tools: ['Python (NLTK/VADER, WordCloud, Streamlit, Pandas, Plotly)'],
        artifact: 'Brand Sentiment Dashboard on Streamlit Cloud with social media monitoring report.',
      },
      {
        title: 'AI Essay Grader for Secondary Schools',
        industry: 'Education',
        brief: 'Build an AI tool grading student essays by rubric criteria (content, grammar, structure, argument) and giving written feedback.',
        howTo: 'Use an LLM with a structured grading prompt. Define a rubric with 4 criteria and point allocations. Build a teacher Streamlit interface for uploading essays and receiving grades and feedback.',
        tools: ['Python', 'OpenAI API', 'Streamlit', 'python-docx'],
        artifact: 'Deployed AI essay grader on Streamlit Cloud and grading accuracy comparison report.',
      },
      {
        title: 'Niger Delta Pipeline Spill Risk Prediction Model',
        industry: 'Oil and Gas / Environment',
        brief: 'Build an ML model predicting oil spill risk scores for Niger Delta pipeline segments based on age, type, and historical incident data.',
        howTo: 'Create a fictional dataset of 200 pipeline segments with age, material, pressure, last inspection date, and community proximity. Train a Risk Score model. Build a Streamlit map dashboard.',
        tools: ['Python (Scikit-learn, Pandas, Folium, Streamlit)'],
        artifact: 'Deployed pipeline risk dashboard on Streamlit Cloud and risk methodology report.',
      },
    ],
    blue: [
      {
        title: 'RAG Document Intelligence System for Nigerian Law Firms',
        industry: 'Legal',
        brief: 'Build a Retrieval-Augmented Generation chatbot allowing Nigerian law firms to query their own legal documents and case files.',
        howTo: 'Ingest sample legal documents (publicly available Nigerian court judgements). Chunk and embed with a text embedding model. Store in a vector database. Build a chat interface for document Q&A.',
        tools: ['Python', 'LangChain', 'OpenAI API', 'Pinecone or ChromaDB', 'Streamlit'],
        artifact: 'Deployed legal document Q&A chatbot on Streamlit Cloud and RAG architecture explainer.',
      },
      {
        title: 'Real-Time Fintech Fraud Detection API',
        industry: 'Fintech / Banking',
        brief: 'Build an ML fraud detection REST API flagging suspicious financial transactions in real time.',
        howTo: 'Train an XGBoost model on a fraud dataset. Handle class imbalance with SMOTE. Build a FastAPI REST endpoint. Containerise with Docker. Write OpenAPI documentation. Test with Postman.',
        tools: ['Python', 'XGBoost', 'Scikit-learn', 'FastAPI', 'Docker', 'Postman'],
        artifact: 'Containerised Fraud Detection API on GitHub with Swagger docs and model performance report.',
      },
      {
        title: 'Manufacturing Defect Detection with Computer Vision',
        industry: 'Manufacturing / Industrial',
        brief: 'Build a computer vision system detecting defects on a fictional factory production line using image classification.',
        howTo: 'Use the MVTec Anomaly Detection dataset or a custom synthetic dataset. Fine-tune a ResNet model for defect vs. no-defect classification. Build a Gradio interface simulating a production line inspector.',
        tools: ['Python', 'PyTorch', 'ResNet', 'Gradio', 'OpenCV', 'Roboflow'],
        artifact: 'Deployed defect detection app on Hugging Face Spaces and model evaluation report.',
      },
      {
        title: 'Oil and Gas Equipment Predictive Maintenance System',
        industry: 'Oil and Gas',
        brief: 'Build a time-series ML system predicting equipment failure for fictional oil field compressors using sensor data.',
        howTo: 'Create a fictional vibration, temperature, and pressure sensor dataset for 5 compressors over 12 months. Train Isolation Forest and LSTM anomaly detectors. Build a Streamlit failure probability dashboard.',
        tools: ['Python (Prophet, TensorFlow/Keras, Streamlit)', 'Grafana (optional)'],
        artifact: 'Predictive maintenance dashboard on Streamlit Cloud and failure alert system documentation.',
      },
      {
        title: 'AI Agricultural Advisory Platform (English and Pidgin)',
        industry: 'Agriculture',
        brief: 'Build an AI advisory system giving Nigerian farmers personalised crop, weather, and market advice via chat in English and Nigerian Pidgin.',
        howTo: 'Build a RAG system using agricultural extension documents as knowledge base. Integrate weather API. Fine-tune responses for Pidgin-friendly output. Deploy as a Streamlit app.',
        tools: ['Python', 'LangChain', 'OpenAI API', 'OpenWeatherMap API', 'Streamlit'],
        artifact: 'Deployed agricultural advisory chatbot on Streamlit Cloud and user testing report.',
      },
      {
        title: 'Malaria Cell Detection Deep Learning System',
        industry: 'Healthcare',
        brief: 'Build a deep learning model detecting malaria-infected red blood cells from microscope slide images: critical for rural Nigerian clinics.',
        howTo: 'Use the NIH Malaria Cell Image Dataset. Fine-tune EfficientNet. Achieve 90%+ accuracy. Add Grad-CAM visualisations for explainability. Deploy as a Gradio web app.',
        tools: ['Python', 'PyTorch', 'EfficientNet', 'Gradio', 'Grad-CAM', 'Hugging Face Spaces'],
        artifact: 'Deployed malaria detection app on Hugging Face Spaces with Grad-CAM visualisations and clinical accuracy report.',
      },
      {
        title: 'Government Citizen Complaint Classification System',
        industry: 'Government',
        brief: 'Build an NLP pipeline automatically classifying, prioritising, and routing citizen complaints to a fictional government agency.',
        howTo: 'Create 1,000 fictional citizen complaints across 6 departments. Train a multi-class text classifier. Build a government officer dashboard with complaint queue by department and urgency.',
        tools: ['Python', 'Scikit-learn or HuggingFace', 'FastAPI', 'Streamlit'],
        artifact: 'Deployed complaint management system on Streamlit Cloud and classification model performance report.',
      },
      {
        title: 'AI Real Estate Property Valuation Tool',
        industry: 'Real Estate',
        brief: 'Build a regression model predicting residential property prices in Port Harcourt or Lagos based on location, size, and amenities.',
        howTo: 'Create a fictional dataset of 2,000 property listings. Engineer features (distance to CBD, room count, estate type). Train a Gradient Boosting model. Build a Streamlit valuation tool.',
        tools: ['Python (LightGBM, Pandas, Folium, Streamlit)'],
        artifact: 'Deployed property valuation tool on Streamlit Cloud and model explainability report (SHAP values).',
      },
      {
        title: 'Nigerian FMCG Retail Demand Forecasting System',
        industry: 'Retail / FMCG',
        brief: 'Build a demand forecasting model for a fictional Nigerian FMCG company predicting product demand across 10 states for the next 30 days.',
        howTo: 'Create 3 years of fictional weekly sales data for 5 products across 10 states. Apply Prophet and SARIMA models. Evaluate forecast accuracy. Build a dashboard for inventory planning.',
        tools: ['Python (Prophet, Statsmodels, Streamlit, Plotly)'],
        artifact: 'Deployed demand forecasting dashboard on Streamlit Cloud and inventory planning report.',
      },
      {
        title: 'AI Code Review Assistant for Nigerian Developers',
        industry: 'Technology / Education',
        brief: 'Build an AI tool reviewing Python or JavaScript code snippets, identifying bugs, and suggesting improvements.',
        howTo: 'Use an LLM with a structured code review prompt. Define review criteria (security, efficiency, readability, best practices). Build a Streamlit interface where developers paste code and receive annotated review.',
        tools: ['Python', 'OpenAI API or CodeLlama', 'Streamlit'],
        artifact: 'Deployed AI code reviewer on Streamlit Cloud and benchmark comparison against manual review.',
      },
    ],
    black: [
      {
        title: 'Autonomous AI Business Process Automation Agent',
        industry: 'Any Enterprise',
        brief: 'Build a multi-step autonomous AI agent receiving a business goal and executing it using tools, web search, and memory.',
        howTo: 'Use LangChain Agents with tool integrations (web search, file write, calculator). Design agent memory and planning loop. Test on 3 business automation scenarios. Monitor with LangSmith.',
        tools: ['Python', 'LangChain Agents', 'LangSmith', 'OpenAI API', 'SerpAPI', 'Streamlit'],
        artifact: 'Deployed autonomous agent demo on Streamlit Cloud with agent execution trace documentation.',
      },
      {
        title: 'Fine-Tuned LLM for Nigerian Legal Document Drafting',
        industry: 'Legal / Government',
        brief: 'Fine-tune a small open-source LLM on Nigerian legal document examples to produce jurisdiction-specific legal drafts.',
        howTo: 'Collect publicly available Nigerian court judgements and regulatory instruments. Prepare fine-tuning dataset. Fine-tune Mistral-7B or Llama 3 using QLoRA. Evaluate on legal drafting benchmarks.',
        tools: ['Python', 'Hugging Face PEFT', 'QLoRA', 'bitsandbytes', 'Weights and Biases'],
        artifact: 'Fine-tuned model on Hugging Face Hub, training report, and benchmark evaluation vs base model.',
      },
      {
        title: 'Multi-Modal Oil Field Safety Inspection AI',
        industry: 'Oil and Gas / Safety',
        brief: 'Build a multi-modal AI system analysing photos of oil field equipment and maintenance logs to flag safety risks.',
        howTo: 'Combine a vision model (CLIP or GPT-4V) for image analysis with an NLP model for log text analysis. Build a Streamlit inspector dashboard where safety officers upload photos and logs.',
        tools: ['Python', 'OpenAI GPT-4V or CLIP', 'Streamlit', 'PyPDF2', 'Pandas'],
        artifact: 'Deployed safety inspection AI on Streamlit Cloud and oil field safety assessment report.',
      },
      {
        title: 'AI Disease Outbreak Early Warning System',
        industry: 'Healthcare / Government',
        brief: 'Build an AI surveillance system detecting unusual disease outbreak patterns from hospital admission data across Nigerian states.',
        howTo: 'Simulate 2 years of fictional weekly disease incidence data across 36 states. Apply time-series anomaly detection. Build an alert dashboard with state-level outbreak heat map.',
        tools: ['Python (Prophet, Isolation Forest, Folium, Streamlit, Plotly)'],
        artifact: 'Deployed disease surveillance dashboard on Streamlit Cloud and public health response protocol.',
      },
      {
        title: 'Enterprise MLOps Model Lifecycle Platform',
        industry: 'Technology / Any',
        brief: 'Build a production-grade MLOps infrastructure covering training, versioning, deployment, monitoring, and automated retraining.',
        howTo: 'Train a baseline model. Set up MLflow. Use DVC for data versioning. Create GitHub Actions CI/CD for automated retraining on drift (Evidently AI). Deploy via BentoML.',
        tools: ['Python', 'MLflow', 'DVC', 'GitHub Actions', 'Docker', 'Evidently AI', 'BentoML'],
        artifact: 'Full MLOps pipeline on GitHub with architecture diagram, drift detection demo, and retraining report.',
      },
      {
        title: 'Voice and Chat Agricultural Extension AI (Pidgin-Enabled)',
        industry: 'Agriculture',
        brief: 'Build a bilingual agricultural advisory AI accessible via chat and voice, targeting smallholder farmers without internet literacy.',
        howTo: 'Build a RAG system with agricultural extension knowledge base. Add text-to-speech (gTTS) for voice output. Add a Pidgin translation layer. Test with 10 real farming questions. Deploy on Streamlit.',
        tools: ['Python', 'LangChain', 'gTTS', 'OpenAI API', 'Streamlit', 'FAISS'],
        artifact: 'Deployed voice and chat agricultural AI on Streamlit Cloud and farmer usability test report.',
      },
      {
        title: 'Urban Traffic Management Computer Vision System',
        industry: 'Government / Transport',
        brief: 'Build a computer vision system detecting vehicle counts, traffic density, and incident types from road camera footage.',
        howTo: 'Use a pre-trained YOLOv8 model for vehicle detection on traffic footage. Build a Streamlit dashboard showing real-time vehicle counts, peak hour detection, and incident flags.',
        tools: ['Python', 'YOLOv8', 'OpenCV', 'Streamlit', 'Plotly'],
        artifact: 'Deployed traffic monitoring app on Streamlit Cloud and urban traffic analysis report.',
      },
      {
        title: 'Adaptive AI Mathematics Tutor for WAEC Students',
        industry: 'Education',
        brief: 'Build an adaptive AI tutor delivering personalised WAEC-level mathematics lessons to Nigerian secondary school students.',
        howTo: 'Define a knowledge graph of WAEC Mathematics topics. Use an LLM to generate questions at the student\'s current level. Track performance. Adjust difficulty. Build a student dashboard.',
        tools: ['Python', 'OpenAI API', 'LangChain', 'Streamlit', 'SQLite (student progress)'],
        artifact: 'Deployed AI mathematics tutor on Streamlit Cloud and learning outcome assessment report.',
      },
      {
        title: 'AI-Driven Corporate ESG Sustainability Report Generator',
        industry: 'Finance / Environment',
        brief: 'Build an AI system analysing a company\'s operational data and automatically generating a GRI Standards-aligned ESG report.',
        howTo: 'Define GRI disclosure categories (energy, emissions, water, labour). Build an LLM pipeline taking raw operational data and generating structured GRI-aligned narrative sections. Add data visualisations.',
        tools: ['Python', 'OpenAI API', 'LangChain', 'Streamlit', 'Matplotlib', 'GRI Standards'],
        artifact: 'Deployed ESG reporting tool on Streamlit Cloud and sample GRI-aligned corporate sustainability report.',
      },
      {
        title: 'AI Innovation Studio: Build a Monetisable African AI Product',
        industry: 'Innovation / Entrepreneurship',
        brief: 'Design, build, and launch a monetisable AI-powered SaaS product targeting a specific Nigerian or African industry pain point.',
        howTo: 'Identify an underserved problem in the Nigerian market. Design the product. Build an MVP using an LLM API. Launch a landing page. Acquire 10 beta users. Document the business model.',
        tools: ['Python', 'OpenAI API or Mistral', 'Streamlit or React', 'Stripe (payment)', 'Vercel'],
        artifact: 'Live AI SaaS MVP, business model canvas, landing page, and first 10 beta user feedback report.',
      },
    ],
  },

  'web-development': {
    green: [
      {
        title: 'Professional Personal Portfolio Website',
        industry: 'Any / Personal Branding',
        brief: 'Build a professional portfolio website showcasing your skills, projects, and contact information.',
        howTo: 'Design and build a responsive multi-page site with Home, About, Projects, and Contact sections. Include smooth scrolling, animations, and a working contact form. Deploy to Netlify or Vercel.',
        tools: ['HTML5', 'CSS3', 'JavaScript', 'TailwindCSS', 'Netlify or Vercel'],
        artifact: 'Live portfolio website on Netlify/Vercel with a Lighthouse performance score of 90+.',
      },
      {
        title: 'Nigerian Restaurant Online Menu and WhatsApp Ordering',
        industry: 'Food and Hospitality',
        brief: 'Build a visually appealing online menu and ordering page for a fictional Nigerian restaurant.',
        howTo: 'Design the site with restaurant branding. Display menu categories (starters, mains, drinks) with photos and prices. Add a cart that totals the order. Link a WhatsApp order button.',
        tools: ['HTML', 'CSS', 'JavaScript or React', 'TailwindCSS', 'Netlify'],
        artifact: 'Live restaurant website on Netlify with full menu and WhatsApp ordering integration.',
      },
      {
        title: 'School Result Checker Web App',
        industry: 'Education',
        brief: 'Build a web app where students enter their exam number to view their results from a fictional secondary school database.',
        howTo: 'Build a React frontend with a search form. Use a JSON file or simple Express API as the "database". Display student name, subject scores, and grade summary on a printable result card.',
        tools: ['React.js', 'Node.js or JSON mock', 'TailwindCSS', 'Vercel'],
        artifact: 'Live result checker app on Vercel with a PDF-printable result card feature.',
      },
      {
        title: 'Agritech Marketplace Landing Page',
        industry: 'Agriculture',
        brief: 'Build a high-converting landing page for a fictional Nigerian agritech startup connecting farmers to buyers.',
        howTo: 'Design a modern landing page with hero section, feature list, testimonials, and CTA. Optimise for mobile. Add a newsletter signup form. Achieve a Lighthouse score of 90+.',
        tools: ['HTML', 'CSS', 'JavaScript', 'TailwindCSS', 'Netlify Forms'],
        artifact: 'Live landing page on Netlify with newsletter signup and Lighthouse performance report.',
      },
      {
        title: 'Community Volunteer Registration and Management System',
        industry: 'Social / Non-Profit',
        brief: 'Build a web app for a fictional Nigerian NGO to manage volunteer sign-ups, roles, and event assignments.',
        howTo: 'Build a React frontend with a volunteer registration form, admin dashboard, and event assignment table. Use localStorage or a JSON API for data persistence.',
        tools: ['React.js', 'TailwindCSS', 'Node.js (Express) or localStorage', 'Vercel'],
        artifact: 'Live volunteer management app on Vercel with admin dashboard and printable volunteer roster.',
      },
      {
        title: 'Weather and Crop Advisory Web App for Farmers',
        industry: 'Agriculture',
        brief: 'Build a web app that shows farmers the current weather for their location and gives simple crop planting advice based on the season.',
        howTo: 'Integrate the OpenWeatherMap API. Let users enter their city. Display temperature, rainfall, and humidity. Add a seasonal crop advisory section using static rule-based logic.',
        tools: ['React.js', 'OpenWeatherMap API', 'TailwindCSS', 'Axios', 'Vercel'],
        artifact: 'Live weather and crop advisory app on Vercel and user testing feedback summary.',
      },
      {
        title: 'Hospital Appointment Booking System',
        industry: 'Healthcare',
        brief: 'Build an online appointment booking system for a fictional Nigerian private hospital.',
        howTo: 'Build a React frontend with doctor selection, calendar date picker, and time slot booking. Use an Express API with a simple JSON store to save and retrieve appointments.',
        tools: ['React.js', 'Node.js (Express)', 'TailwindCSS', 'date-fns', 'Vercel'],
        artifact: 'Live hospital booking app on Vercel with appointment confirmation email or receipt page.',
      },
      {
        title: 'Nigerian Youth Job Board Web App',
        industry: 'Human Resources / Social',
        brief: 'Build a simple job board web app targeting Nigerian youth, listing entry-level and internship positions.',
        howTo: 'Build a React frontend showing job cards with company, role, location, and type filters. Use a JSON file or Airtable API as data source. Add a simple job application modal.',
        tools: ['React.js', 'TailwindCSS', 'Airtable API or JSON', 'Vercel'],
        artifact: 'Live job board on Vercel with filter functionality and job application flow.',
      },
      {
        title: 'Oil and Gas Company Corporate Website',
        industry: 'Oil and Gas',
        brief: 'Build a professional multi-page corporate website for a fictional Nigerian oil services company.',
        howTo: 'Build a responsive 5-page site (Home, Services, Projects, About, Contact) with SEO meta tags, a contact form, and a project gallery. Deploy with a custom domain simulation.',
        tools: ['HTML', 'CSS', 'JavaScript or React', 'TailwindCSS', 'Netlify'],
        artifact: 'Live corporate website on Netlify with Lighthouse performance report and SEO audit.',
      },
      {
        title: 'Personal Budget Tracker Progressive Web App',
        industry: 'Fintech / Personal',
        brief: 'Build a personal finance progressive web app (PWA) that works offline, tracking income, expenses, and monthly balance.',
        howTo: 'Build a React PWA with income and expense entry forms, category tagging, and a monthly summary dashboard. Implement service worker for offline support and localStorage for data persistence.',
        tools: ['React.js', 'TailwindCSS', 'Service Worker API', 'Chart.js', 'Vercel'],
        artifact: 'Live PWA on Vercel with offline capability, installable on mobile, and budget analytics dashboard.',
      },
    ],
    blue: [
      {
        title: 'Full-Stack E-Commerce Platform with Paystack Integration',
        industry: 'Retail / E-Commerce',
        brief: 'Build a full-stack e-commerce platform for a fictional Nigerian fashion brand with product listings, cart, checkout, and Paystack payment integration.',
        howTo: 'Build a Next.js frontend with Supabase backend. Implement product CRUD, cart state, user auth, and Paystack payment gateway. Add an admin dashboard for inventory management.',
        tools: ['Next.js', 'Supabase', 'Paystack API', 'TailwindCSS', 'Vercel'],
        artifact: 'Live e-commerce platform on Vercel with Paystack test checkout flow and admin dashboard.',
      },
      {
        title: 'Hospital Patient Management System',
        industry: 'Healthcare',
        brief: 'Build a full-stack patient management system for a fictional Nigerian clinic with patient records, appointment scheduling, and billing.',
        howTo: 'Build a Next.js app with Supabase database. Implement patient registration, appointment booking, visit notes, and invoice generation. Add role-based access for doctors and receptionists.',
        tools: ['Next.js', 'Supabase', 'TailwindCSS', 'Prisma', 'Vercel'],
        artifact: 'Live patient management system on Vercel with role-based access demo and database schema documentation.',
      },
      {
        title: 'Agritech Farm Management and Marketplace Platform',
        industry: 'Agriculture',
        brief: 'Build a dual-sided platform where Nigerian farmers manage their farm records and list produce for sale to buyers.',
        howTo: 'Build a React/Next.js app with Supabase. Farmer dashboard: crop planting log, harvest tracker, expense record. Buyer marketplace: browse listings, send purchase requests.',
        tools: ['Next.js', 'Supabase', 'TailwindCSS', 'Node.js', 'Vercel'],
        artifact: 'Live farm management and marketplace platform on Vercel with farmer and buyer demo accounts.',
      },
      {
        title: 'Real-Time Community Emergency Alert System',
        industry: 'Government / Social',
        brief: 'Build a real-time emergency alert web app for Nigerian community leaders to broadcast flood, fire, and security alerts to residents.',
        howTo: 'Build a Next.js app with Supabase Realtime for live alert push. Alert admin creates and broadcasts. Residents subscribe by location and see alerts in real time. Add SMS fallback via Termii.',
        tools: ['Next.js', 'Supabase Realtime', 'Termii SMS API', 'TailwindCSS', 'Vercel'],
        artifact: 'Live emergency alert system on Vercel with real-time broadcast demo and SMS integration report.',
      },
      {
        title: 'Oil and Gas Contractor Management Web Portal',
        industry: 'Oil and Gas',
        brief: 'Build a web portal for a fictional oil services company to manage contractors: onboarding, document submission, and compliance tracking.',
        howTo: 'Build a full-stack Next.js app with Supabase. Contractor portal: profile, document upload, status tracking. Admin portal: review documents, approve/reject, flag compliance gaps.',
        tools: ['Next.js', 'Supabase Storage', 'TailwindCSS', 'Vercel'],
        artifact: 'Live contractor portal on Vercel with document upload flow and admin compliance dashboard.',
      },
      {
        title: 'EdTech Learning Management System',
        industry: 'Education',
        brief: 'Build a full-featured LMS for a fictional Nigerian online school with course content, quizzes, and student progress tracking.',
        howTo: 'Build a Next.js LMS with Supabase. Course builder: lessons (text and video embed), quiz with auto-grading. Student dashboard: progress bar, certificate on course completion.',
        tools: ['Next.js', 'Supabase', 'TailwindCSS', 'Vimeo or YouTube embed', 'Vercel'],
        artifact: 'Live LMS on Vercel with a full demo course, quiz flow, and certificate generation.',
      },
      {
        title: 'Nigerian Fintech Personal Finance Dashboard',
        industry: 'Fintech',
        brief: 'Build a full-stack personal finance dashboard integrating with a mock open banking API to display accounts, transactions, and spending analytics.',
        howTo: 'Build a Next.js frontend with Supabase auth. Integrate Mono or a mock bank API for account data. Display spending by category, monthly trends, and savings goals.',
        tools: ['Next.js', 'Supabase', 'Mono API or mock', 'Chart.js / Recharts', 'Vercel'],
        artifact: 'Live personal finance dashboard on Vercel with bank connection demo and analytics walkthrough.',
      },
      {
        title: 'Real Estate Property Listing and Agent Platform',
        industry: 'Real Estate',
        brief: 'Build a full-stack property listing platform for the Nigerian market where agents list properties and buyers search and enquire.',
        howTo: 'Build a Next.js app with Supabase. Agent portal: list property (photos via Supabase Storage, price, location, type). Buyer search: filter by location, price, type. Enquiry messaging system.',
        tools: ['Next.js', 'Supabase', 'Google Maps API', 'TailwindCSS', 'Vercel'],
        artifact: 'Live property listing platform on Vercel with agent and buyer demo accounts and map integration.',
      },
      {
        title: 'Multi-Vendor Restaurant Ordering Platform',
        industry: 'Food and Hospitality',
        brief: 'Build a multi-vendor food ordering platform like a mini Jumia Food, where multiple restaurants list menus and customers order from them.',
        howTo: 'Build a Next.js app with Supabase. Restaurant vendor portal: manage menu items. Customer app: browse restaurants, add to cart, checkout with Paystack. Order tracking page.',
        tools: ['Next.js', 'Supabase', 'Paystack', 'TailwindCSS', 'Vercel'],
        artifact: 'Live multi-vendor food platform on Vercel with 3 demo restaurants and Paystack checkout.',
      },
      {
        title: 'Government Open Data Transparency Portal',
        industry: 'Government',
        brief: 'Build a public-facing data portal for a fictional Nigerian state government publishing budget, project, and performance data in open formats.',
        howTo: 'Build a Next.js data portal with Supabase. Admin uploads datasets (CSV). Public portal shows searchable tables, charts, and downloadable data. Add API endpoints for programmatic access.',
        tools: ['Next.js', 'Supabase', 'Recharts', 'Papa Parse', 'Vercel'],
        artifact: 'Live open data portal on Vercel with sample government datasets, visualisations, and public API.',
      },
    ],
    black: [
      {
        title: 'Production SaaS Platform with Multi-Tenancy and Billing',
        industry: 'Technology / Innovation',
        brief: 'Build a production-grade multi-tenant SaaS platform with team workspaces, role-based access control, subscription billing via Paystack, and a usage analytics dashboard.',
        howTo: 'Architect a Next.js app with Supabase Row Level Security for tenant isolation. Implement Paystack subscription plans. Build team invite flow and admin billing portal. Monitor with Vercel Analytics.',
        tools: ['Next.js', 'Supabase', 'Paystack Subscriptions', 'TailwindCSS', 'Vercel Analytics'],
        artifact: 'Live SaaS platform on Vercel with multi-tenancy demo, billing flow, and architecture documentation.',
      },
      {
        title: 'Full-Stack Fintech App with NDIC-Aligned Compliance Features',
        industry: 'Fintech / Banking',
        brief: 'Build a production-grade fintech web app with KYC verification, transaction monitoring, and NDPA 2023-compliant data handling.',
        howTo: 'Build a Next.js fintech app with Supabase. Implement KYC upload (ID + selfie), transaction limits and flagging logic, NDPA consent management, and audit log for all data access.',
        tools: ['Next.js', 'Supabase', 'Cloudinary (KYC storage)', 'TailwindCSS', 'Vercel'],
        artifact: 'Live fintech app on Vercel with KYC flow, compliance dashboard, and NDPA data handling documentation.',
      },
      {
        title: 'AI-Powered Content Publishing Platform',
        industry: 'Media / Technology',
        brief: 'Build a full-stack content publishing platform with an integrated AI writing assistant, SEO optimisation, and a monetised subscription reader model.',
        howTo: 'Build a Next.js CMS with Supabase. Editor: rich text + OpenAI-powered writing assistant (continue, rephrase, summarise). Reader: free and paid tiers via Paystack. Auto-generate SEO meta.',
        tools: ['Next.js', 'Supabase', 'OpenAI API', 'Paystack', 'TipTap editor', 'Vercel'],
        artifact: 'Live publishing platform on Vercel with AI writing demo, paywalled reader, and SEO report.',
      },
      {
        title: 'Healthcare Telemedicine Platform',
        industry: 'Healthcare',
        brief: 'Build a full telemedicine web platform where patients book video consultations with doctors, receive prescriptions, and pay online.',
        howTo: 'Build a Next.js app with Supabase. Patient portal: register, book appointment, pay with Paystack, join video call (Whereby or Daily.co embed). Doctor portal: manage schedule, write notes, issue prescription.',
        tools: ['Next.js', 'Supabase', 'Paystack', 'Whereby or Daily.co API', 'TailwindCSS', 'Vercel'],
        artifact: 'Live telemedicine platform on Vercel with end-to-end consultation demo and doctor dashboard.',
      },
      {
        title: 'Supply Chain Visibility and Logistics Tracking Platform',
        industry: 'Logistics / Retail',
        brief: 'Build a real-time supply chain visibility platform for a fictional Nigerian FMCG company tracking shipments from warehouse to retailer.',
        howTo: 'Build a Next.js app with Supabase Realtime. Warehouse staff: dispatch and status update. Logistics tracker: GPS waypoint updates. Retailer dashboard: live shipment map and ETA.',
        tools: ['Next.js', 'Supabase Realtime', 'Leaflet.js / Mapbox', 'TailwindCSS', 'Vercel'],
        artifact: 'Live logistics tracking platform on Vercel with real-time map demo and supply chain analytics.',
      },
      {
        title: 'Agricultural Cooperative Digital Banking Platform',
        industry: 'Agriculture / Fintech',
        brief: 'Build a digital banking micro-platform for a Nigerian farming cooperative: member savings, loan applications, and group fund management.',
        howTo: 'Build a Next.js app with Supabase. Member portal: savings deposit/withdrawal history, loan application form, repayment schedule. Admin portal: approve loans, track fund balance, generate reports.',
        tools: ['Next.js', 'Supabase', 'Paystack', 'Chart.js', 'Vercel'],
        artifact: 'Live cooperative banking platform on Vercel with full loan cycle demo and audit report export.',
      },
      {
        title: 'Real-Time Collaborative Project Management Tool',
        industry: 'Technology / Any',
        brief: 'Build a real-time collaborative project management web app (Trello-like) with boards, tasks, team members, and live updates.',
        howTo: 'Build a Next.js app with Supabase Realtime. Create boards, columns, and draggable task cards. Team invite via email. All changes broadcast live to all connected users. Activity feed.',
        tools: ['Next.js', 'Supabase Realtime', 'dnd-kit (drag and drop)', 'TailwindCSS', 'Vercel'],
        artifact: 'Live project management tool on Vercel with real-time collaboration demo (2 browser windows).',
      },
      {
        title: 'Oil and Gas HSE Incident Reporting and Analytics Platform',
        industry: 'Oil and Gas',
        brief: 'Build a full digital HSE incident reporting and analytics platform for a fictional Nigerian oil services company.',
        howTo: 'Build a Next.js app with Supabase. Field worker: submit incident report (type, location, severity, photos). HSE manager: investigate, update status, generate trend analytics. Export reports to PDF.',
        tools: ['Next.js', 'Supabase Storage', 'Recharts', 'PDFKit or Puppeteer', 'Vercel'],
        artifact: 'Live HSE platform on Vercel with full incident lifecycle demo and analytics dashboard.',
      },
      {
        title: 'Government Tax Filing Self-Service Portal',
        industry: 'Government / Fintech',
        brief: 'Build a self-service tax filing web portal for a fictional Nigerian state revenue authority.',
        howTo: 'Build a Next.js portal with Supabase. Taxpayer registration, income declaration form, tax computation engine, payment via Paystack, and receipt generation. Admin review and audit queue.',
        tools: ['Next.js', 'Supabase', 'Paystack', 'TailwindCSS', 'Vercel'],
        artifact: 'Live tax filing portal on Vercel with full taxpayer journey demo and revenue analytics dashboard.',
      },
      {
        title: 'Full-Stack EdTech Startup: Launch a Monetised Online Course Platform',
        industry: 'Education / Innovation',
        brief: 'Design, build, and launch a production-ready monetised online course platform targeting a specific Nigerian professional audience.',
        howTo: 'Build a Next.js LMS with Supabase. Course builder (lessons, quizzes, certificates). Student portal with progress tracking. Paystack subscription or per-course payment. Marketing landing page.',
        tools: ['Next.js', 'Supabase', 'Paystack', 'TailwindCSS', 'Vercel', 'OpenAI (optional)'],
        artifact: 'Live monetised course platform on Vercel with a full demo course, payment flow, and launch strategy document.',
      },
    ],
  },
}
