export interface SpecialDomain {
  icon: string
  title: string
  teaser: string
  desc: string
  color: string
  curriculum: string[]
  tools: string[]
  careers: string[]
}

export const SPECIAL_DOMAINS: SpecialDomain[] = [
  {
    icon: '📱',
    title: 'Digital Marketing & Growth',
    teaser: 'Drive real business results with Google Ads, Meta Ads, SEO and content strategy.',
    color: '#E87722',
    desc: 'Master the full digital marketing toolkit used by agencies and growth teams across Nigeria and globally.',
    curriculum: [
      'Social Media Strategy and Content Calendar Planning',
      'SEO Fundamentals: Keywords, On-Page and Off-Page Optimisation',
      'Google Ads: Search, Display and Performance Max Campaigns',
      'Meta Ads: Facebook and Instagram Campaign Management',
      'Email Marketing: Mailchimp Sequences and Automation',
      'Google Analytics 4 and Meta Business Insights',
      'Content Creation: Canva, Copywriting and Brand Voice',
      'Capstone: Full 90-Day Digital Marketing Plan for a Nigerian Business',
    ],
    tools: ['Meta Ads Manager', 'Google Ads', 'Mailchimp', 'Canva', 'Google Analytics 4'],
    careers: ['Digital Marketing Executive', 'Social Media Manager', 'Growth Marketer', 'Marketing Analyst'],
  },
  {
    icon: '🎨',
    title: 'UI/UX Design',
    teaser: 'Design digital products people love — from first sketch to polished Figma prototype.',
    color: '#7C3AED',
    desc: 'Learn the complete user-centred design process used at the world\'s most valued tech companies.',
    curriculum: [
      'Design Thinking and the Human-Centred Design Framework',
      'User Research: Interviews, Surveys and Persona Development',
      'Information Architecture and User Journey Mapping',
      'Wireframing: Low-Fidelity and High-Fidelity Prototypes in Figma',
      'Visual Design: Colour Theory, Typography, Spacing and Hierarchy',
      'Design Systems: Component Libraries and Style Guides',
      'Usability Testing with Maze and Iterative Design',
      'Capstone: End-to-End UX Case Study for a Mobile App',
    ],
    tools: ['Figma', 'FigJam', 'Maze', 'Miro', 'Lottie Files'],
    careers: ['UI/UX Designer', 'Product Designer', 'UX Researcher', 'Design Lead'],
  },
  {
    icon: '🤝',
    title: 'Virtual Assistance & Remote Work',
    teaser: 'Get hired by international clients and build a thriving remote career from anywhere in Nigeria.',
    color: '#0891B2',
    desc: 'Develop the in-demand skills, tools and professional presence that global businesses pay top dollar for.',
    curriculum: [
      'The Virtual Assistant Profession: Services, Niches and Rates',
      'Core VA Skills: Email, Calendar, Travel and Task Management',
      'Tools of the Trade: Notion, Trello, Asana, Slack and Zoom',
      'Client Communication: Professionalism, Reporting and Boundaries',
      'Finding Clients on Upwork, Fiverr, LinkedIn and Direct Outreach',
      'Proposal Writing, Contracts and Invoicing with Wave or PayPal',
      'Specialised VA Skills: Social Media, Research and Data Entry',
      'Building Your VA Brand and Scaling to an Agency',
    ],
    tools: ['Notion', 'Trello', 'Asana', 'Slack', 'Zoom', 'Google Workspace', 'Calendly'],
    careers: ['Virtual Assistant', 'Remote Executive Assistant', 'Online Business Manager', 'Freelance VA'],
  },
  {
    icon: '🐍',
    title: 'Python Programming',
    teaser: 'Learn Africa\'s most in-demand programming language and automate everything from spreadsheets to web scraping.',
    color: '#2563EB',
    desc: 'A practical Python course built for working professionals who want to add real coding ability to their skill set.',
    curriculum: [
      'Python Setup: Installing Python, VS Code and Virtual Environments',
      'Syntax, Variables, Data Types and Operators',
      'Control Flow: If-Else, For Loops and While Loops',
      'Functions, Modules and the Python Standard Library',
      'File Handling: Reading and Writing CSV, JSON and Text Files',
      'Web Scraping with BeautifulSoup and Requests',
      'Introduction to Pandas: DataFrames and Basic Data Analysis',
      'Capstone: Build a Python Automation Tool for a Real Business Problem',
    ],
    tools: ['Python 3', 'VS Code', 'Jupyter Notebook', 'Pandas', 'Requests', 'BeautifulSoup'],
    careers: ['Python Developer', 'Automation Specialist', 'Junior Data Scientist', 'Backend Intern'],
  },
  {
    icon: '☁️',
    title: 'Cloud Computing Fundamentals',
    teaser: 'Understand AWS, Azure and Google Cloud — the infrastructure powering every modern business.',
    color: '#0D4F5C',
    desc: 'Get foundational cloud knowledge that opens doors to DevOps, cloud administration and systems architecture roles.',
    curriculum: [
      'Cloud Concepts: IaaS, PaaS, SaaS and Deployment Models',
      'AWS Core Services: EC2, S3, RDS, Lambda and IAM',
      'Azure Fundamentals: Virtual Machines, Blob Storage and Azure AD',
      'GCP Essentials: Compute Engine, Cloud Storage and BigQuery',
      'Networking in the Cloud: VPCs, Subnets and Security Groups',
      'Serverless Computing: AWS Lambda and Azure Functions',
      'Cloud Cost Management and the Well-Architected Framework',
      'Capstone: Deploy a Three-Tier Application on AWS or Azure',
    ],
    tools: ['AWS Console', 'Azure Portal', 'Google Cloud Console', 'Terraform (Intro)', 'Docker Basics'],
    careers: ['Cloud Support Engineer', 'Cloud Administrator', 'DevOps Intern', 'IT Infrastructure Analyst'],
  },
  {
    icon: '🖌️',
    title: 'Graphic Design',
    teaser: 'Create stunning visuals for brands, social media and marketing without expensive software.',
    color: '#BE185D',
    desc: 'A practical design programme for entrepreneurs, marketers and creatives who want to produce professional-grade visuals.',
    curriculum: [
      'Design Principles: Composition, Contrast, Alignment and Repetition',
      'Colour Theory: Palettes, Brand Colour Systems and Psychology',
      'Typography: Font Pairing, Hierarchy and Readability',
      'Canva Pro: Templates, Brand Kit and Advanced Features',
      'Adobe Express: Posters, Banners and Social Media Graphics',
      'Logo Design and Basic Brand Identity Creation',
      'Print Design: Flyers, Business Cards and Brochures',
      'Capstone: Complete Brand Identity Package for a Nigerian Business',
    ],
    tools: ['Canva Pro', 'Adobe Express', 'Adobe Photoshop (Basics)', 'Google Fonts', 'Coolors'],
    careers: ['Graphic Designer', 'Brand Designer', 'Social Media Designer', 'Marketing Creative'],
  },
  {
    icon: '🎬',
    title: 'Video Editing & Content Creation',
    teaser: 'Produce professional-grade videos and grow an engaged audience on YouTube, Instagram and TikTok.',
    color: '#BE123C',
    desc: 'The complete content creator toolkit — from filming and editing to publishing and monetisation strategy.',
    curriculum: [
      'Storytelling Fundamentals: Scripts, Storyboards and Shot Lists',
      'Smartphone Filming: Lighting, Sound and Camera Techniques',
      'CapCut: Mobile Video Editing, Transitions and Effects',
      'DaVinci Resolve: Professional Desktop Editing and Colour Grading',
      'YouTube Strategy: SEO, Thumbnails and Publishing Workflow',
      'Instagram Reels and TikTok: Short-Form Content and Trending Formats',
      'Voiceover, Captions and Accessibility for African Audiences',
      'Capstone: Produce and Publish a 3-Video Content Series',
    ],
    tools: ['CapCut', 'DaVinci Resolve', 'Canva', 'YouTube Studio', 'TikTok Creator Center'],
    careers: ['Video Editor', 'Content Creator', 'Social Media Manager', 'YouTube Channel Manager'],
  },
  {
    icon: '📑',
    title: 'Microsoft Office Mastery',
    teaser: 'Become an advanced Microsoft Office user and multiply your productivity at work.',
    color: '#15803d',
    desc: 'Go beyond the basics and master the Office tools that employers look for in every professional role.',
    curriculum: [
      'Microsoft Word: Styles, Table of Contents, Templates and Mail Merge',
      'Excel Advanced Functions: XLOOKUP, IFS, SUMIFS and Dynamic Arrays',
      'Excel PivotTables and Charts for Business Reporting',
      'PowerPoint: Slide Design, Animations and Executive Presentations',
      'Outlook: Calendar Management, Rules and Professional Email Etiquette',
      'OneDrive and SharePoint: Cloud Collaboration and File Management',
      'Microsoft Forms and Teams for Surveys and Virtual Meetings',
      'Capstone: Build a Professional Business Report and Presentation',
    ],
    tools: ['Microsoft Word', 'Excel', 'PowerPoint', 'Outlook', 'Teams', 'OneDrive', 'SharePoint'],
    careers: ['Executive Assistant', 'Office Manager', 'Administrative Officer', 'Business Analyst'],
  },
  {
    icon: '📲',
    title: 'Mobile App Development',
    teaser: 'Build and publish your own mobile app to the Google Play Store and Apple App Store.',
    color: '#7C3AED',
    desc: 'A hands-on Flutter programme that takes you from zero to a published, real-world mobile application.',
    curriculum: [
      'Dart Language: Syntax, Types, Functions and Object-Oriented Concepts',
      'Flutter Setup: SDK, Android Studio and Device Emulators',
      'Widgets: Stateless, Stateful and the Flutter Widget Tree',
      'Navigation: Routes, Named Routes and Bottom Navigation Bar',
      'State Management with Provider and Riverpod',
      'Firebase: Authentication, Firestore Database and Push Notifications',
      'REST API Integration and JSON Data Handling in Flutter',
      'Capstone: Build and Publish a Mobile App to the Play Store',
    ],
    tools: ['Flutter', 'Dart', 'Firebase', 'Android Studio', 'VS Code', 'Google Play Console'],
    careers: ['Mobile App Developer', 'Flutter Developer', 'App Entrepreneur', 'Junior Android Developer'],
  },
  {
    icon: '🛒',
    title: 'E-Commerce & Online Business',
    teaser: 'Launch and grow a profitable online store or freelance business from anywhere in Nigeria.',
    color: '#B45309',
    desc: 'Learn how successful Nigerian entrepreneurs build online businesses that generate income in naira and dollars.',
    curriculum: [
      'E-Commerce Models: Dropshipping, Print-on-Demand, Digital Products and Services',
      'Setting Up a Shopify or Paystack Commerce Store',
      'Product Research and Supplier Sourcing (Local and AliExpress)',
      'Payment Integration: Paystack, Flutterwave and Dollar Payments',
      'Instagram and TikTok Shop: Selling Through Social Commerce',
      'Customer Service, Order Fulfilment and Returns Management',
      'Marketing Your Store: Organic Content, Paid Ads and Email Lists',
      'Capstone: Launch a Live Online Store with Your First Product Listed',
    ],
    tools: ['Shopify', 'Paystack Commerce', 'Canva', 'Meta Ads Manager', 'Google Merchant Center'],
    careers: ['E-Commerce Entrepreneur', 'Dropshipping Business Owner', 'Online Store Manager', 'Digital Product Creator'],
  },
]
